'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { createClient } from '../../lib/supabase/client';
import { DEMO_MASTER_ID } from '../../lib/demo/config';
import { resetDemo } from '../../lib/demo/client';
import styles from '../master-projects/[id]/deliverables/review-deliverables.module.css';

type Tab='slr'|'matrix'|'clarifications'|'rfi'|'checklist'|'ve'|'bid-internal'|'bid-report'|'internal';
type ActionType='RBB'|'CL'|'RFI'|'VE'|'SLC';
type Master={id:string;project_number:string;name:string;location:string;status:string;revision:string;version_date:string|null;systems:string[]};
type Finding={id:string;display_number:string;scope_item:string;systems:string[];status:string};
type Action={id:string;related_master_finding_id:string|null;deliverable_type:ActionType;sequence_number:number;display_number:string;system_name:string;title:string;content:string;impact_considerations:string;reference:string;status:string;response:string;response_date:string|null;response_source:string;client_facing:boolean;sort_order:number};
type Checklist={id:string;linked_master_finding_id:string|null;sequence_number:number;display_number:string;category:string;system_name:string;question:string;status:string;response:string;response_reason:string;sort_order:number};
type Bid={id:string;related_deliverable_id:string|null;bidder_name:string;scope_item:string;proposal_status:string;proposal_reference:string;clarification:string;documented_adjustment:number|null;adjustment_type:string;pricing_source:string;internal_notes:string;client_notes:string;sort_order:number};

const pad=(n:number)=>String(n).padStart(3,'0');
const blankAction=(type:ActionType)=>({related_master_finding_id:null as string|null,deliverable_type:type,system_name:'Other',title:'',content:'',impact_considerations:'',reference:'',status:type==='VE'?'Identified':type==='RBB'?'Current':'Draft',response:'',response_date:null as string|null,response_source:'',client_facing:type!=='SLC'});
const blankChecklist=()=>({linked_master_finding_id:null as string|null,category:'Project-Specific',system_name:'General',question:'',status:'Open',response:'',response_reason:''});
const blankBid=()=>({related_deliverable_id:null as string|null,bidder_name:'',scope_item:'',proposal_status:'Unclear',proposal_reference:'',clarification:'',documented_adjustment:'',adjustment_type:'None',pricing_source:'',internal_notes:'',client_notes:''});

export default function DemoDeliverablesClient(){
 const supabase=useMemo(()=>createClient(),[]);
 const [master,setMaster]=useState<Master|null>(null);const [findings,setFindings]=useState<Finding[]>([]);const [actions,setActions]=useState<Action[]>([]);const [checklist,setChecklist]=useState<Checklist[]>([]);const [bids,setBids]=useState<Bid[]>([]);
 const [tab,setTab]=useState<Tab>('slr');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [message,setMessage]=useState('');const [resetOpen,setResetOpen]=useState(false);
 const [actionOpen,setActionOpen]=useState(false);const [editingAction,setEditingAction]=useState<Action|null>(null);const [actionDraft,setActionDraft]=useState(blankAction('RBB'));
 const [checkOpen,setCheckOpen]=useState(false);const [editingCheck,setEditingCheck]=useState<Checklist|null>(null);const [checkDraft,setCheckDraft]=useState(blankChecklist());
 const [bidOpen,setBidOpen]=useState(false);const [editingBid,setEditingBid]=useState<Bid|null>(null);const [bidDraft,setBidDraft]=useState(blankBid());

 const load=useCallback(async()=>{setLoading(true);setError('');const [m,f,a,c,b]=await Promise.all([
  supabase.from('master_projects').select('*').eq('id',DEMO_MASTER_ID).maybeSingle(),
  supabase.from('master_project_findings').select('*').eq('master_project_id',DEMO_MASTER_ID).order('sequence_number'),
  supabase.from('master_project_deliverable_items').select('*').eq('master_project_id',DEMO_MASTER_ID).order('deliverable_type').order('sequence_number'),
  supabase.from('master_project_checklist_items').select('*').eq('master_project_id',DEMO_MASTER_ID).order('sequence_number'),
  supabase.from('master_project_bid_alignment_items').select('*').eq('master_project_id',DEMO_MASTER_ID).order('bidder_name').order('sort_order')
 ]);setLoading(false);const e=m.error||f.error||a.error||c.error||b.error;if(e){setError(e.message);return;}setMaster(m.data as Master);setFindings((f.data||[]) as Finding[]);setActions((a.data||[]) as Action[]);setChecklist((c.data||[]) as Checklist[]);setBids((b.data||[]) as Bid[]);},[supabase]);
 useEffect(()=>{void load()},[load]);
 const findingMap=useMemo(()=>new Map(findings.map(x=>[x.id,x])),[findings]);const actionMap=useMemo(()=>new Map(actions.map(x=>[x.id,x])),[actions]);
 const byType=(type:ActionType)=>actions.filter(x=>x.deliverable_type===type).sort((a,b)=>a.sequence_number-b.sequence_number);
 const relatedSlr=(id:string|null)=>id&&findingMap.get(id)?`${findingMap.get(id)!.display_number} — ${findingMap.get(id)!.scope_item}`:'—';
 const startAction=(type:ActionType)=>{setEditingAction(null);setActionDraft(blankAction(type));setActionOpen(true)};const editAction=(x:Action)=>{setEditingAction(x);setActionDraft({...x});setActionOpen(true)};
 const saveAction=async()=>{if(!actionDraft.title.trim()||!actionDraft.content.trim()){setError('Title and content are required.');return;}let result:any;if(editingAction){result=await supabase.from('master_project_deliverable_items').update({related_master_finding_id:actionDraft.related_master_finding_id,system_name:actionDraft.system_name,title:actionDraft.title.trim(),content:actionDraft.content.trim(),impact_considerations:actionDraft.impact_considerations.trim(),reference:actionDraft.reference.trim(),status:actionDraft.status,response:actionDraft.response.trim(),response_date:actionDraft.response_date||null,response_source:actionDraft.response_source.trim(),client_facing:actionDraft.client_facing}).eq('id',editingAction.id);}else{const seq=Math.max(0,...actions.filter(x=>x.deliverable_type===actionDraft.deliverable_type).map(x=>x.sequence_number))+1;result=await supabase.from('master_project_deliverable_items').insert({owner_id:'demo-presenter',master_project_id:DEMO_MASTER_ID,created_by_user_id:'demo-presenter',...actionDraft,sequence_number:seq,display_number:`${actionDraft.deliverable_type==='SLC'?'IC':actionDraft.deliverable_type}-${pad(seq)}`,title:actionDraft.title.trim(),content:actionDraft.content.trim(),reference:actionDraft.reference.trim(),sort_order:seq});}if(result.error){setError(result.error.message);return;}setActionOpen(false);setEditingAction(null);setMessage('Deliverable item saved.');await load();};
 const deleteAction=async()=>{if(!editingAction)return;const r=await supabase.from('master_project_deliverable_items').delete().eq('id',editingAction.id);if(r.error){setError(r.error.message);return;}setActionOpen(false);setEditingAction(null);await load();};
 const startCheck=()=>{setEditingCheck(null);setCheckDraft(blankChecklist());setCheckOpen(true)};const editCheck=(x:Checklist)=>{setEditingCheck(x);setCheckDraft({...x});setCheckOpen(true)};
 const saveCheck=async()=>{if(!checkDraft.question.trim()){setError('Contractor confirmation text is required.');return;}let r:any;if(editingCheck)r=await supabase.from('master_project_checklist_items').update(checkDraft).eq('id',editingCheck.id);else{const seq=Math.max(0,...checklist.map(x=>x.sequence_number))+1;r=await supabase.from('master_project_checklist_items').insert({owner_id:'demo-presenter',master_project_id:DEMO_MASTER_ID,created_by_user_id:'demo-presenter',...checkDraft,sequence_number:seq,display_number:`CSC-${pad(seq)}`,sort_order:seq});}if(r.error){setError(r.error.message);return;}setCheckOpen(false);setEditingCheck(null);await load();};
 const deleteCheck=async()=>{if(!editingCheck)return;const r=await supabase.from('master_project_checklist_items').delete().eq('id',editingCheck.id);if(r.error){setError(r.error.message);return;}setCheckOpen(false);setEditingCheck(null);await load();};
 const startBid=()=>{setEditingBid(null);setBidDraft(blankBid());setBidOpen(true)};const editBid=(x:Bid)=>{setEditingBid(x);setBidDraft({...x,documented_adjustment:x.documented_adjustment==null?'':String(x.documented_adjustment)});setBidOpen(true)};
 const saveBid=async()=>{if(!bidDraft.bidder_name.trim()||!bidDraft.scope_item.trim()){setError('Bidder and scope item are required.');return;}const payload={related_deliverable_id:bidDraft.related_deliverable_id,bidder_name:bidDraft.bidder_name.trim(),scope_item:bidDraft.scope_item.trim(),proposal_status:bidDraft.proposal_status,proposal_reference:bidDraft.proposal_reference.trim(),clarification:bidDraft.clarification.trim(),documented_adjustment:bidDraft.documented_adjustment===''?null:Number(bidDraft.documented_adjustment),adjustment_type:bidDraft.adjustment_type,pricing_source:bidDraft.pricing_source.trim(),internal_notes:bidDraft.internal_notes.trim(),client_notes:bidDraft.client_notes.trim()};let r:any;if(editingBid)r=await supabase.from('master_project_bid_alignment_items').update(payload).eq('id',editingBid.id);else r=await supabase.from('master_project_bid_alignment_items').insert({...payload,owner_id:'demo-presenter',master_project_id:DEMO_MASTER_ID,created_by_user_id:'demo-presenter',sort_order:bids.length+1});if(r.error){setError(r.error.message);return;}setBidOpen(false);setEditingBid(null);await load();};
 const deleteBid=async()=>{if(!editingBid)return;const r=await supabase.from('master_project_bid_alignment_items').delete().eq('id',editingBid.id);if(r.error){setError(r.error.message);return;}setBidOpen(false);setEditingBid(null);await load();};
 if(loading&&!master)return <main className={styles.loading}>Loading deliverables…</main>;if(!master)return <main className={styles.loading}>Deliverables unavailable.</main>;
 const projectTitle=`${master.project_number} · ${master.name}`;const today=new Date().toLocaleDateString();
 const tabs:[Tab,string][]=[['slr','SLR Register'],['matrix','Scope Matrix / RBB'],['clarifications','GC Clarifications'],['rfi','Formal RFIs'],['ve','VE Opportunities'],['checklist','Contractor Checklist'],['bid-internal','Bid Alignment — Internal'],['bid-report','Bid Alignment Report'],['internal','Internal Actions']];
 return <main className={styles.shell}>
  <aside className={styles.sidebar}><div className={styles.brand}><img src="/demo/icon.png" alt=""/><div><b>Technology Preconstruction</b><span>Deliverables Workspace</span></div></div><a className={styles.back} href="/">← Project / Estimating</a><div className={styles.project}><span>{master.project_number}</span><b>{master.name}</b><small>{master.revision} · {master.status}</small></div><nav>{tabs.map(([id,label])=><button key={id} className={tab===id?styles.active:''} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className={styles.account}><span>DEMO</span><b>Browser-local presentation</b><button onClick={()=>setResetOpen(true)}>Reset Demo</button></div></aside>
  <section className={styles.main}><header className={styles.topbar}><div><span className={styles.eyebrow}>DELIVERABLES WORKSPACE</span><h1>{master.name}</h1><p>SLR → RBB / Clarification / RFI / VE / Contractor Confirmation → Bid Alignment</p></div><div className={styles.topActions}><span>{master.status}</span><button onClick={()=>window.print()}>Print / Save PDF</button></div></header>{error?<div className={styles.error}>{error}<button onClick={()=>setError('')}>×</button></div>:null}{message?<div className={styles.message}>{message}<button onClick={()=>setMessage('')}>×</button></div>:null}
  {tab==='slr'?<Workspace title="SLR Register" eyebrow="INTERNAL SOURCE RECORD" subtitle="Each SLR records a documented scope risk. Downstream deliverables remain separately numbered and traceable back to the SLR."><table className={styles.table}><thead><tr><th>SLR</th><th>Systems</th><th>Scope Item / Topic</th><th>Status</th><th>Downstream Records</th></tr></thead><tbody>{findings.map(f=>{const children=actions.filter(a=>a.related_master_finding_id===f.id).map(a=>a.display_number);const checks=checklist.filter(c=>c.linked_master_finding_id===f.id).map(c=>c.display_number);return <tr key={f.id}><td><b>{f.display_number}</b></td><td>{(f.systems||[]).join(', ')}</td><td><b>{f.scope_item}</b></td><td>{f.status}</td><td>{[...children,...checks].join(', ')||'—'}</td></tr>})}</tbody></table></Workspace>:null}
  {tab==='matrix'?<Workspace title="Scope Matrix / Recommended Base Bid" eyebrow="CLIENT DELIVERABLE" subtitle="Uniform base-bid instructions generated from documented project review findings." action="Add RBB" onAction={()=>startAction('RBB')}><DocHeader title="Scope Matrix / Recommended Base Bid" project={projectTitle} revision={master.revision} date={today}/><table className={styles.table}><thead><tr><th>RBB</th><th>System</th><th>Scope Item</th><th>Recommended Base Bid</th><th>References</th><th>Status</th><th className={styles.noPrint}>Edit</th></tr></thead><tbody>{byType('RBB').filter(x=>x.client_facing).map(x=><tr key={x.id}><td><b>{x.display_number}</b></td><td>{x.system_name}</td><td><b>{x.title}</b><small>{relatedSlr(x.related_master_finding_id)}</small></td><td>{x.content}</td><td>{x.reference||'—'}</td><td>{x.status}</td><td className={styles.noPrint}><button onClick={()=>editAction(x)}>Edit</button></td></tr>)}</tbody></table></Workspace>:null}
  {tab==='clarifications'?<Workspace title="GC Clarification Log" eyebrow="GC WORKING DELIVERABLE" subtitle="Internal trade responsibility or scope-basis confirmations that do not require an Owner/A/E decision." action="Add GC Clarification" onAction={()=>startAction('CL')}><DocHeader title="GC Clarification Log" project={projectTitle} revision={master.revision} date={today}/><table className={styles.table}><thead><tr><th>CL</th><th>System</th><th>Subject</th><th>Clarification</th><th>Reference</th><th>Status</th><th>Response</th><th className={styles.noPrint}>Edit</th></tr></thead><tbody>{byType('CL').filter(x=>x.client_facing).map(x=><tr key={x.id}><td><b>{x.display_number}</b></td><td>{x.system_name}</td><td><b>{x.title}</b><small>{relatedSlr(x.related_master_finding_id)}</small></td><td>{x.content}</td><td>{x.reference||'—'}</td><td>{x.status}</td><td>{x.response||'—'}</td><td className={styles.noPrint}><button onClick={()=>editAction(x)}>Edit</button></td></tr>)}</tbody></table></Workspace>:null}
  {tab==='rfi'?<Workspace title="Formal RFI Register" eyebrow="OWNER / A/E CLARIFICATION" subtitle="Formal design questions are used only where the contract documents require an Owner/A/E decision." action="Add RFI" onAction={()=>startAction('RFI')}><DocHeader title="Formal RFI Register" project={projectTitle} revision={master.revision} date={today}/><table className={styles.table}><thead><tr><th>RFI</th><th>System</th><th>Subject</th><th>Question</th><th>Reference</th><th>Status</th><th>Response</th><th className={styles.noPrint}>Edit</th></tr></thead><tbody>{byType('RFI').filter(x=>x.client_facing).map(x=><tr key={x.id}><td><b>{x.display_number}</b></td><td>{x.system_name}</td><td><b>{x.title}</b><small>{relatedSlr(x.related_master_finding_id)}</small></td><td>{x.content}</td><td>{x.reference||'—'}</td><td>{x.status}</td><td>{x.response||'—'}</td><td className={styles.noPrint}><button onClick={()=>editAction(x)}>Edit</button></td></tr>)}</tbody></table></Workspace>:null}
  {tab==='ve'?<Workspace title="VE Opportunity Log" eyebrow="OPTIONAL ALTERNATIVE" subtitle="VE remains separate from the compliant base bid and is not treated as an omission." action="Add VE" onAction={()=>startAction('VE')}><DocHeader title="VE Opportunity Log" project={projectTitle} revision={master.revision} date={today}/><div className={styles.cards}>{byType('VE').filter(x=>x.client_facing).map(x=><article className={styles.card} key={x.id}><div className={styles.cardTitle}><div><span>{x.display_number} · {x.system_name}</span><h3>{x.title}</h3></div><span>{x.status}</span></div><dl><div><dt>VE Opportunity</dt><dd>{x.content}</dd></div><div><dt>Potential Impact / Considerations</dt><dd>{x.impact_considerations||'—'}</dd></div><div><dt>References</dt><dd>{x.reference||'—'}</dd></div><div><dt>Related SLR</dt><dd>{relatedSlr(x.related_master_finding_id)}</dd></div></dl><button className={styles.noPrint} onClick={()=>editAction(x)}>Edit</button></article>)}</div></Workspace>:null}
  {tab==='checklist'?<Workspace title="Contractor Scope Confirmation Checklist" eyebrow="CLIENT / BIDDER DELIVERABLE" subtitle="Bidder confirmations use CSC numbering and remain separate from GC Clarifications." action="Add Confirmation" onAction={startCheck}><DocHeader title="Contractor Scope Confirmation Checklist" project={projectTitle} revision={master.revision} date={today}/><table className={styles.table}><thead><tr><th>CSC</th><th>Category</th><th>System</th><th>Contractor Confirmation</th><th>Response</th><th>Contractor Notes</th><th className={styles.noPrint}>Edit</th></tr></thead><tbody>{checklist.map(x=><tr key={x.id}><td><b>{x.display_number}</b></td><td>{x.category}</td><td>{x.system_name}</td><td><b>{x.question}</b><small>{relatedSlr(x.linked_master_finding_id)}</small></td><td>{x.response||'Yes / No / Qualified'}</td><td>{x.response_reason||''}</td><td className={styles.noPrint}><button onClick={()=>editCheck(x)}>Edit</button></td></tr>)}</tbody></table></Workspace>:null}
  {tab==='bid-internal'?<Workspace title="Bid Alignment — Internal" eyebrow="INTERNAL WORKSPACE" subtitle="Compare bidder proposals to the established scope basis and document only supported adders or credits." action="Add Bid Item" onAction={startBid}><table className={styles.table}><thead><tr><th>Bidder</th><th>Scope Item</th><th>RBB / Source</th><th>Status</th><th>Proposal Reference</th><th>Clarification</th><th>Documented Adjustment</th><th>Pricing Source</th><th className={styles.noPrint}>Edit</th></tr></thead><tbody>{bids.map(x=>{const rel=x.related_deliverable_id?actionMap.get(x.related_deliverable_id):null;const amt=x.documented_adjustment==null?'Unpriced':`${x.adjustment_type==='Deduct'?'-':x.adjustment_type==='Add'?'+':''}$${Number(x.documented_adjustment).toLocaleString()}`;return <tr key={x.id}><td><b>{x.bidder_name}</b></td><td>{x.scope_item}</td><td>{rel?.display_number||'—'}</td><td>{x.proposal_status}</td><td>{x.proposal_reference||'—'}</td><td>{x.clarification||'—'}</td><td>{amt}</td><td>{x.pricing_source||'—'}</td><td className={styles.noPrint}><button onClick={()=>editBid(x)}>Edit</button></td></tr>})}</tbody></table></Workspace>:null}
  {tab==='bid-report'?<Workspace title="Bid Alignment Report" eyebrow="CLIENT DELIVERABLE" subtitle="External bidder comparison based on documented proposal scope and documented pricing only."><DocHeader title="Bid Alignment Report" project={projectTitle} revision={master.revision} date={today}/><table className={styles.table}><thead><tr><th>Bidder</th><th>Scope Item</th><th>RBB / Source</th><th>Alignment</th><th>Documented Adjustment</th><th>Client Note</th></tr></thead><tbody>{bids.map(x=>{const rel=x.related_deliverable_id?actionMap.get(x.related_deliverable_id):null;const amt=x.documented_adjustment==null?'Unpriced':`${x.adjustment_type==='Deduct'?'-':x.adjustment_type==='Add'?'+':''}$${Number(x.documented_adjustment).toLocaleString()}`;return <tr key={x.id}><td><b>{x.bidder_name}</b></td><td>{x.scope_item}</td><td>{rel?.display_number||'—'}</td><td>{x.proposal_status}</td><td>{amt}</td><td>{x.client_notes||'—'}</td></tr>})}</tbody></table></Workspace>:null}
  {tab==='internal'?<Workspace title="SLR Action Register" eyebrow="INTERNAL ONLY" subtitle="Complete action register tying RBB, CL, RFI, VE and internal clarification records back to each originating SLR." action="Add Internal Clarification" onAction={()=>startAction('SLC')}><table className={styles.table}><thead><tr><th>ID</th><th>Type</th><th>Related SLR</th><th>System</th><th>Title</th><th>Content</th><th>Status</th><th>Client Facing</th><th className={styles.noPrint}>Edit</th></tr></thead><tbody>{[...actions].sort((a,b)=>a.sort_order-b.sort_order).map(x=><tr key={x.id}><td><b>{x.display_number}</b></td><td>{x.deliverable_type==='SLC'?'Internal Clarification':x.deliverable_type}</td><td>{relatedSlr(x.related_master_finding_id)}</td><td>{x.system_name}</td><td>{x.title}</td><td>{x.content}</td><td>{x.status}</td><td>{x.client_facing?'Yes':'No'}</td><td className={styles.noPrint}><button onClick={()=>editAction(x)}>Edit</button></td></tr>)}</tbody></table></Workspace>:null}
  </section>
  {resetOpen?<Modal title="Reset Demo" close={()=>setResetOpen(false)} save={resetDemo}><p>Reset all browser-local changes and restore the fictional starting project?</p></Modal>:null}
  {actionOpen?<Modal title={editingAction?`Edit ${editingAction.display_number}`:`Add ${actionDraft.deliverable_type}`} close={()=>setActionOpen(false)} save={()=>void saveAction()} deleteLabel={editingAction?'Delete':undefined} onDelete={editingAction?()=>void deleteAction():undefined}><label>Related SLR<select value={actionDraft.related_master_finding_id||''} onChange={e=>{const id=e.target.value||null;const f=id?findingMap.get(id):null;setActionDraft(d=>({...d,related_master_finding_id:id,system_name:f?.systems?.[0]||d.system_name,title:d.title||f?.scope_item||''}))}}><option value="">None</option>{findings.map(f=><option key={f.id} value={f.id}>{f.display_number} — {f.scope_item}</option>)}</select></label><label>System<input value={actionDraft.system_name} onChange={e=>setActionDraft(d=>({...d,system_name:e.target.value}))}/></label><label>Title / Scope Item<input value={actionDraft.title} onChange={e=>setActionDraft(d=>({...d,title:e.target.value}))}/></label><label>{actionDraft.deliverable_type==='VE'?'VE Opportunity':actionDraft.deliverable_type==='RBB'?'Recommended Base Bid':actionDraft.deliverable_type==='RFI'?'RFI Question':actionDraft.deliverable_type==='CL'?'GC Clarification':'Internal Clarification'}<textarea rows={5} value={actionDraft.content} onChange={e=>setActionDraft(d=>({...d,content:e.target.value}))}/></label>{actionDraft.deliverable_type==='VE'?<label>Potential Impact / Considerations<textarea rows={4} value={actionDraft.impact_considerations} onChange={e=>setActionDraft(d=>({...d,impact_considerations:e.target.value}))}/></label>:null}<label>References<textarea rows={2} value={actionDraft.reference} onChange={e=>setActionDraft(d=>({...d,reference:e.target.value}))}/></label><div className={styles.formRow}><label>Status<input value={actionDraft.status} onChange={e=>setActionDraft(d=>({...d,status:e.target.value}))}/></label><label className={styles.check}><input type="checkbox" checked={actionDraft.client_facing} onChange={e=>setActionDraft(d=>({...d,client_facing:e.target.checked}))}/> Client Facing</label></div>{['CL','RFI'].includes(actionDraft.deliverable_type)?<><label>Response<textarea rows={3} value={actionDraft.response} onChange={e=>setActionDraft(d=>({...d,response:e.target.value}))}/></label><div className={styles.formRow}><label>Response Date<input type="date" value={actionDraft.response_date||''} onChange={e=>setActionDraft(d=>({...d,response_date:e.target.value||null}))}/></label><label>Response Source<input value={actionDraft.response_source} onChange={e=>setActionDraft(d=>({...d,response_source:e.target.value}))}/></label></div></>:null}</Modal>:null}
  {checkOpen?<Modal title={editingCheck?`Edit ${editingCheck.display_number}`:'Add Contractor Confirmation'} close={()=>setCheckOpen(false)} save={()=>void saveCheck()} deleteLabel={editingCheck?'Delete':undefined} onDelete={editingCheck?()=>void deleteCheck():undefined}><label>Related SLR<select value={checkDraft.linked_master_finding_id||''} onChange={e=>{const id=e.target.value||null;const f=id?findingMap.get(id):null;setCheckDraft(d=>({...d,linked_master_finding_id:id,system_name:f?.systems?.[0]||d.system_name}))}}><option value="">None</option>{findings.map(f=><option key={f.id} value={f.id}>{f.display_number} — {f.scope_item}</option>)}</select></label><div className={styles.formRow}><label>Category<input value={checkDraft.category} onChange={e=>setCheckDraft(d=>({...d,category:e.target.value}))}/></label><label>System<input value={checkDraft.system_name} onChange={e=>setCheckDraft(d=>({...d,system_name:e.target.value}))}/></label></div><label>Contractor Confirmation<textarea rows={4} value={checkDraft.question} onChange={e=>setCheckDraft(d=>({...d,question:e.target.value}))}/></label><div className={styles.formRow}><label>Status<input value={checkDraft.status} onChange={e=>setCheckDraft(d=>({...d,status:e.target.value}))}/></label><label>Response<input value={checkDraft.response} onChange={e=>setCheckDraft(d=>({...d,response:e.target.value}))}/></label></div><label>Contractor Notes<textarea rows={3} value={checkDraft.response_reason} onChange={e=>setCheckDraft(d=>({...d,response_reason:e.target.value}))}/></label></Modal>:null}
  {bidOpen?<Modal title={editingBid?'Edit Bid Alignment Item':'Add Bid Alignment Item'} close={()=>setBidOpen(false)} save={()=>void saveBid()} deleteLabel={editingBid?'Delete':undefined} onDelete={editingBid?()=>void deleteBid():undefined}><div className={styles.formRow}><label>Bidder<input value={bidDraft.bidder_name} onChange={e=>setBidDraft(d=>({...d,bidder_name:e.target.value}))}/></label><label>Proposal Status<select value={bidDraft.proposal_status} onChange={e=>setBidDraft(d=>({...d,proposal_status:e.target.value}))}>{['Included','Excluded','Qualified','Unclear'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Scope Item<input value={bidDraft.scope_item} onChange={e=>setBidDraft(d=>({...d,scope_item:e.target.value}))}/></label><label>Related RBB / Source<select value={bidDraft.related_deliverable_id||''} onChange={e=>setBidDraft(d=>({...d,related_deliverable_id:e.target.value||null}))}><option value="">None</option>{byType('RBB').map(x=><option key={x.id} value={x.id}>{x.display_number} — {x.title}</option>)}</select></label><label>Proposal Reference<input value={bidDraft.proposal_reference} onChange={e=>setBidDraft(d=>({...d,proposal_reference:e.target.value}))}/></label><label>Clarification<textarea rows={3} value={bidDraft.clarification} onChange={e=>setBidDraft(d=>({...d,clarification:e.target.value}))}/></label><div className={styles.formRow}><label>Documented Adjustment<input type="number" value={bidDraft.documented_adjustment} onChange={e=>setBidDraft(d=>({...d,documented_adjustment:e.target.value}))}/></label><label>Adjustment Type<select value={bidDraft.adjustment_type} onChange={e=>setBidDraft(d=>({...d,adjustment_type:e.target.value}))}>{['None','Add','Deduct'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Pricing Source<input value={bidDraft.pricing_source} onChange={e=>setBidDraft(d=>({...d,pricing_source:e.target.value}))}/></label><label>Internal Notes<textarea rows={3} value={bidDraft.internal_notes} onChange={e=>setBidDraft(d=>({...d,internal_notes:e.target.value}))}/></label><label>Client Note<textarea rows={3} value={bidDraft.client_notes} onChange={e=>setBidDraft(d=>({...d,client_notes:e.target.value}))}/></label></Modal>:null}
 </main>;
}

function Workspace({title,eyebrow,subtitle,action,onAction,children}:{title:string;eyebrow:string;subtitle:string;action?:string;onAction?:()=>void;children:React.ReactNode}){return <section className={styles.workspace}><div className={styles.workspaceHead}><div><span>{eyebrow}</span><h2>{title}</h2><p>{subtitle}</p></div>{action&&onAction?<button className={styles.primary} onClick={onAction}>{action}</button>:null}</div>{children}</section>}
function DocHeader({title,project,revision,date}:{title:string;project:string;revision:string;date:string}){return <div className={styles.documentHeader}><img src="/demo/wordmark.png" alt="Technology Preconstruction Workspace"/><div><b>{title}</b><span>{project}</span><span>{revision} · {date}</span></div></div>}
function Modal({title,children,close,save,deleteLabel,onDelete}:{title:string;children:React.ReactNode;close:()=>void;save:()=>void;deleteLabel?:string;onDelete?:()=>void}){return <div className={styles.modalBackdrop}><section className={styles.modal}><header><h2>{title}</h2><button onClick={close}>×</button></header><div className={styles.form}>{children}</div><footer>{deleteLabel&&onDelete?<button className={styles.danger} onClick={onDelete}>{deleteLabel}</button>:<span/>}<div><button onClick={close}>Cancel</button><button className={styles.primary} onClick={save}>Save</button></div></footer></section></div>}
