'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { createClient } from '../../../../lib/supabase/client';
import styles from './review-deliverables.module.css';

type Props={masterProjectId:string;actualUserId:string;workspaceOwnerId:string;role:string;userName:string};
type Tab='notes'|'matrix'|'clarifications'|'checklist'|'ve'|'bid-internal'|'bid-report'|'internal';
type ActionType='RBB'|'CL'|'RFI'|'VE'|'SLC';
type Master={id:string;project_number:string;name:string;location:string;status:string;revision:string;version_date:string|null;systems:string[]};
type Finding={id:string;display_number:string;scope_item:string;systems:string[];status:string};
type Action={id:string;related_master_finding_id:string|null;deliverable_type:ActionType;sequence_number:number;display_number:string;system_name:string;title:string;content:string;impact_considerations:string;reference:string;status:string;response:string;response_date:string|null;response_source:string;client_facing:boolean;sort_order:number};
type Checklist={id:string;linked_master_finding_id:string|null;sequence_number:number;display_number:string;category:string;system_name:string;question:string;status:string;response:string;response_reason:string;sort_order:number};
type Note={id:string;system_name:string;topic:string;source_type:string;source_reference:string;observation:string;snippet_label:string;disposition:string;linked_master_finding_id:string|null;created_at:string};
type Bid={id:string;related_deliverable_id:string|null;bidder_name:string;scope_item:string;proposal_status:string;proposal_reference:string;clarification:string;documented_adjustment:number|null;adjustment_type:string;pricing_source:string;internal_notes:string;client_notes:string;sort_order:number};

const blankAction=(type:ActionType):Omit<Action,'id'|'sequence_number'|'display_number'|'sort_order'>=>({related_master_finding_id:null,deliverable_type:type,system_name:'Other',title:'',content:'',impact_considerations:'',reference:'',status:type==='VE'?'Identified':type==='RBB'?'Current':'Draft',response:'',response_date:null,response_source:'',client_facing:type!=='SLC'});
const blankChecklist=()=>({linked_master_finding_id:null,category:'Project-Specific',system_name:'General',question:'',status:'Open',response:'',response_reason:''});
const blankNote=()=>({system_name:'Other',topic:'',source_type:'Specification',source_reference:'',observation:'',snippet_label:'',disposition:'Unreviewed',linked_master_finding_id:null as string|null});
const blankBid=()=>({related_deliverable_id:null as string|null,bidder_name:'',scope_item:'',proposal_status:'Unclear',proposal_reference:'',clarification:'',documented_adjustment:'' as string|number,adjustment_type:'None',pricing_source:'',internal_notes:'',client_notes:''});
const pad=(n:number)=>String(n).padStart(3,'0');

function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'blue'|'green'|'amber'|'red'|'internal'}){return <span className={`${styles.badge} ${styles[`badge_${tone}`]}`}>{children}</span>}

export default function ReviewDeliverablesClient({masterProjectId,actualUserId,workspaceOwnerId,userName}:Props){
 const supabase=useMemo(()=>createClient(),[]);
 const [master,setMaster]=useState<Master|null>(null); const [findings,setFindings]=useState<Finding[]>([]); const [actions,setActions]=useState<Action[]>([]); const [checklist,setChecklist]=useState<Checklist[]>([]); const [notes,setNotes]=useState<Note[]>([]); const [bids,setBids]=useState<Bid[]>([]);
 const [tab,setTab]=useState<Tab>('matrix'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [message,setMessage]=useState('');
 const [editingAction,setEditingAction]=useState<Action|null>(null); const [actionDraft,setActionDraft]=useState(blankAction('RBB')); const [showAction,setShowAction]=useState(false);
 const [editingChecklist,setEditingChecklist]=useState<Checklist|null>(null); const [checkDraft,setCheckDraft]=useState(blankChecklist()); const [showChecklist,setShowChecklist]=useState(false);
 const [noteDraft,setNoteDraft]=useState(blankNote()); const [showNote,setShowNote]=useState(false);
 const [editingBid,setEditingBid]=useState<Bid|null>(null); const [bidDraft,setBidDraft]=useState(blankBid()); const [showBid,setShowBid]=useState(false);

 const load=useCallback(async()=>{setLoading(true);setError(''); const [m,f,a,c,n,b]=await Promise.all([
   supabase.from('master_projects').select('id,project_number,name,location,status,revision,version_date,systems').eq('id',masterProjectId).maybeSingle(),
   supabase.from('master_project_findings').select('id,display_number,scope_item,systems,status').eq('master_project_id',masterProjectId).order('sequence_number'),
   supabase.from('master_project_deliverable_items').select('*').eq('master_project_id',masterProjectId).order('deliverable_type').order('sequence_number'),
   supabase.from('master_project_checklist_items').select('*').eq('master_project_id',masterProjectId).order('sequence_number'),
   supabase.from('master_project_review_notes').select('*').eq('master_project_id',masterProjectId).order('created_at'),
   supabase.from('master_project_bid_alignment_items').select('*').eq('master_project_id',masterProjectId).order('bidder_name').order('sort_order')
 ]); setLoading(false); const err=m.error||f.error||a.error||c.error||n.error||b.error; if(err){setError(err.message);return;} if(!m.data){setError('Master Project not found or unavailable.');return;} setMaster({...m.data,systems:Array.isArray(m.data.systems)?m.data.systems:[]} as Master); setFindings((f.data||[]).map((x:any)=>({...x,systems:Array.isArray(x.systems)?x.systems:[]})) as Finding[]); setActions((a.data||[]) as Action[]); setChecklist((c.data||[]) as Checklist[]); setNotes((n.data||[]) as Note[]); setBids((b.data||[]) as Bid[]);
 },[masterProjectId,supabase]); useEffect(()=>{void load()},[load]);

 const findingMap=useMemo(()=>new Map(findings.map(x=>[x.id,x])),[findings]);
 const actionMap=useMemo(()=>new Map(actions.map(x=>[x.id,x])),[actions]);
 const byType=(type:ActionType)=>actions.filter(x=>x.deliverable_type===type).sort((a,b)=>a.sequence_number-b.sequence_number);
 const nextSequence=(type:ActionType)=>Math.max(0,...actions.filter(x=>x.deliverable_type===type).map(x=>x.sequence_number))+1;
 const openNewAction=(type:ActionType)=>{setEditingAction(null);setActionDraft(blankAction(type));setShowAction(true)};
 const openEditAction=(item:Action)=>{setEditingAction(item);setActionDraft({...item});setShowAction(true)};
 const saveAction=async()=>{if(!actionDraft.title.trim())return setError('Title / Scope Item is required.');if(!actionDraft.content.trim())return setError(`${actionDraft.deliverable_type} content is required.`);setError('');let result:any;if(editingAction){result=await supabase.from('master_project_deliverable_items').update({related_master_finding_id:actionDraft.related_master_finding_id,system_name:actionDraft.system_name,title:actionDraft.title.trim(),content:actionDraft.content.trim(),impact_considerations:actionDraft.impact_considerations.trim(),reference:actionDraft.reference.trim(),status:actionDraft.status,response:actionDraft.response.trim(),response_date:actionDraft.response_date||null,response_source:actionDraft.response_source.trim(),client_facing:actionDraft.client_facing,updated_at:new Date().toISOString()}).eq('id',editingAction.id);}else{const seq=nextSequence(actionDraft.deliverable_type);result=await supabase.from('master_project_deliverable_items').insert({owner_id:workspaceOwnerId,master_project_id:masterProjectId,created_by_user_id:actualUserId,related_master_finding_id:actionDraft.related_master_finding_id,deliverable_type:actionDraft.deliverable_type,sequence_number:seq,display_number:`${actionDraft.deliverable_type}-${pad(seq)}`,system_name:actionDraft.system_name,title:actionDraft.title.trim(),content:actionDraft.content.trim(),impact_considerations:actionDraft.impact_considerations.trim(),reference:actionDraft.reference.trim(),status:actionDraft.status,response:actionDraft.response.trim(),response_date:actionDraft.response_date||null,response_source:actionDraft.response_source.trim(),client_facing:actionDraft.client_facing,sort_order:seq});} if(result.error)return setError(result.error.message);setShowAction(false);setEditingAction(null);await load();setMessage('Deliverable item saved.')};
 const deleteAction=async(item:Action)=>{if(!confirm(`Delete ${item.display_number}?`))return;const {error:e}=await supabase.from('master_project_deliverable_items').delete().eq('id',item.id);if(e)return setError(e.message);await load();setMessage(`${item.display_number} deleted.`)};

 const openNewChecklist=()=>{setEditingChecklist(null);setCheckDraft(blankChecklist());setShowChecklist(true)}; const openEditChecklist=(x:Checklist)=>{setEditingChecklist(x);setCheckDraft({...x});setShowChecklist(true)};
 const saveChecklist=async()=>{if(!checkDraft.question.trim())return setError('Checklist question is required.');let result:any;if(editingChecklist){result=await supabase.from('master_project_checklist_items').update({linked_master_finding_id:checkDraft.linked_master_finding_id,category:checkDraft.category,system_name:checkDraft.system_name,question:checkDraft.question.trim(),status:checkDraft.status,response:checkDraft.response,response_reason:checkDraft.response_reason,updated_at:new Date().toISOString()}).eq('id',editingChecklist.id);}else{const seq=Math.max(0,...checklist.map(x=>x.sequence_number))+1;result=await supabase.from('master_project_checklist_items').insert({owner_id:workspaceOwnerId,master_project_id:masterProjectId,created_by_user_id:actualUserId,linked_master_finding_id:checkDraft.linked_master_finding_id,sequence_number:seq,display_number:`CSC-${pad(seq)}`,sort_order:seq,category:checkDraft.category,system_name:checkDraft.system_name,question:checkDraft.question.trim(),status:checkDraft.status,response:checkDraft.response,response_reason:checkDraft.response_reason});}if(result.error)return setError(result.error.message);setShowChecklist(false);await load();setMessage('Contractor confirmation saved.')};
 const deleteChecklist=async(x:Checklist)=>{if(!confirm(`Delete ${x.display_number}?`))return;const {error:e}=await supabase.from('master_project_checklist_items').delete().eq('id',x.id);if(e)return setError(e.message);await load()};

 const saveNote=async()=>{if(!noteDraft.topic.trim()||!noteDraft.observation.trim())return setError('Review note topic and observation are required.');const {error:e}=await supabase.from('master_project_review_notes').insert({owner_id:workspaceOwnerId,master_project_id:masterProjectId,created_by_user_id:actualUserId,...noteDraft,topic:noteDraft.topic.trim(),source_reference:noteDraft.source_reference.trim(),observation:noteDraft.observation.trim()});if(e)return setError(e.message);setShowNote(false);setNoteDraft(blankNote());await load();setMessage('Review note saved.')};
 const deleteNote=async(x:Note)=>{if(!confirm('Delete this review note?'))return;const {error:e}=await supabase.from('master_project_review_notes').delete().eq('id',x.id);if(e)return setError(e.message);await load()};

 const openNewBid=()=>{setEditingBid(null);setBidDraft(blankBid());setShowBid(true)}; const openEditBid=(x:Bid)=>{setEditingBid(x);setBidDraft({...x,documented_adjustment:x.documented_adjustment??''});setShowBid(true)};
 const saveBid=async()=>{if(!bidDraft.bidder_name.trim()||!bidDraft.scope_item.trim())return setError('Bidder and Scope Item are required.');const payload={related_deliverable_id:bidDraft.related_deliverable_id,bidder_name:bidDraft.bidder_name.trim(),scope_item:bidDraft.scope_item.trim(),proposal_status:bidDraft.proposal_status,proposal_reference:bidDraft.proposal_reference.trim(),clarification:bidDraft.clarification.trim(),documented_adjustment:bidDraft.documented_adjustment===''?null:Number(bidDraft.documented_adjustment),adjustment_type:bidDraft.adjustment_type,pricing_source:bidDraft.pricing_source.trim(),internal_notes:bidDraft.internal_notes.trim(),client_notes:bidDraft.client_notes.trim(),updated_at:new Date().toISOString()};let result:any;if(editingBid)result=await supabase.from('master_project_bid_alignment_items').update(payload).eq('id',editingBid.id);else result=await supabase.from('master_project_bid_alignment_items').insert({...payload,owner_id:workspaceOwnerId,master_project_id:masterProjectId,created_by_user_id:actualUserId,sort_order:bids.length+1});if(result.error)return setError(result.error.message);setShowBid(false);await load();setMessage('Bid alignment item saved.')};
 const deleteBid=async(x:Bid)=>{if(!confirm('Delete this bid-alignment item?'))return;const {error:e}=await supabase.from('master_project_bid_alignment_items').delete().eq('id',x.id);if(e)return setError(e.message);await load()};

 if(loading&&!master)return <main className={styles.loading}>Loading review deliverables…</main>; if(error&&!master)return <main className={styles.loading}><h2>Review Deliverables unavailable</h2><p>{error}</p><a href={`/master-projects/${masterProjectId}`}>Return to Master Project</a></main>; if(!master)return null;
 const projectTitle=`${master.project_number} · ${master.name}`; const today=new Date().toLocaleDateString();
 const renderRefSlr=(id:string|null)=>id&&findingMap.get(id)?`${findingMap.get(id)!.display_number} — ${findingMap.get(id)!.scope_item}`:'—';
 const print=()=>window.print();

 return <main className={styles.shell}>
  <aside className={styles.sidebar}>
   <div className={styles.brand}><img src="/brand/scopelogic-logo-mark.png" alt=""/><div><b>ScopeLogic</b><span>Review Deliverables</span></div></div>
   <a className={styles.back} href={`/master-projects/${masterProjectId}`}>← Master Project</a>
   <div className={styles.project}><span>{master.project_number}</span><b>{master.name}</b><small>{master.revision} · {master.status}</small></div>
   <nav>{([['notes','Review Notes'],['matrix','ScopeLogic Matrix™'],['clarifications','Clarification Log™'],['checklist','Contractor Checklist'],['ve','VE Opportunity Log'],['bid-internal','Bid Alignment — Internal'],['bid-report','Bid Alignment Report'],['internal','Internal Actions']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?styles.active:''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
   <div className={styles.account}><span>ACCOUNT</span><b>{userName}</b></div>
  </aside>
  <section className={styles.main}>
   <header className={styles.topbar}><div><span className={styles.eyebrow}>PRODUCTION REVIEW WORKFLOW</span><h1>{master.name}</h1><p>{master.location||'No location entered'} · {master.revision}</p></div><div className={styles.topActions}><Badge tone="green">{master.status}</Badge><button onClick={print}>Print / Save PDF</button></div></header>
   {error?<div className={styles.error}>{error}<button onClick={()=>setError('')}>×</button></div>:null}{message?<div className={styles.message}>{message}<button onClick={()=>setMessage('')}>×</button></div>:null}

   {tab==='notes'?<section className={styles.workspace}><Header eyebrow="INTERNAL REVIEW" title="Review Notes" subtitle="Capture source observations before or while developing SLRs." action="Add Review Note" onAction={()=>setShowNote(true)}/><div className={styles.cards}>{notes.length?notes.map(n=><article className={styles.card} key={n.id}><div className={styles.cardTitle}><div><span>{n.system_name} · {n.source_type}</span><h3>{n.topic}</h3></div><Badge>{n.disposition}</Badge></div><p>{n.observation}</p><dl><div><dt>Source Reference</dt><dd>{n.source_reference||'—'}</dd></div><div><dt>Related SLR</dt><dd>{renderRefSlr(n.linked_master_finding_id)}</dd></div></dl><button className={styles.linkButton} onClick={()=>void deleteNote(n)}>Delete</button></article>):<Empty text="No structured review notes yet. Your legacy Internal Notes remain unchanged in the Master Project."/>}</div></section>:null}

   {tab==='matrix'?<section className={styles.workspace}><Header eyebrow="CLIENT DELIVERABLE" title="ScopeLogic Matrix™" subtitle="Recommended Base Bid entries. RBBs remain separate records tied to their originating SLR." action="Add RBB" onAction={()=>openNewAction('RBB')}/><DocumentHeader title="ScopeLogic Matrix™" project={projectTitle} revision={master.revision} date={today}/><table className={styles.table}><thead><tr><th>RBB</th><th>System</th><th>Scope Item</th><th>Recommended Base Bid</th><th>References</th><th>Status</th><th className={styles.noPrint}>Edit</th></tr></thead><tbody>{byType('RBB').filter(x=>x.client_facing).map(x=><tr key={x.id}><td><b>{x.display_number}</b></td><td>{x.system_name}</td><td><b>{x.title}</b><small>{renderRefSlr(x.related_master_finding_id)}</small></td><td>{x.content}</td><td>{x.reference||'—'}</td><td>{x.status}</td><td className={styles.noPrint}><button onClick={()=>openEditAction(x)}>Edit</button></td></tr>)}</tbody></table></section>:null}

   {tab==='clarifications'?<section className={styles.workspace}><Header eyebrow="CLIENT DELIVERABLE" title="Clarification Log™" subtitle="Formal RFIs and GC Clarifications in one controlled log. Type remains independently numbered." action="Add Clarification" onAction={()=>openNewAction('CL')}/><div className={styles.inlineActions}><button onClick={()=>openNewAction('RFI')}>+ Formal RFI</button></div><DocumentHeader title="Clarification Log™" project={projectTitle} revision={master.revision} date={today}/><table className={styles.table}><thead><tr><th>ID</th><th>Type</th><th>System</th><th>Subject</th><th>Clarification / Question</th><th>Reference</th><th>Status</th><th>Response</th><th className={styles.noPrint}>Edit</th></tr></thead><tbody>{actions.filter(x=>['CL','RFI'].includes(x.deliverable_type)&&x.client_facing).sort((a,b)=>a.deliverable_type.localeCompare(b.deliverable_type)||a.sequence_number-b.sequence_number).map(x=><tr key={x.id}><td><b>{x.display_number}</b></td><td>{x.deliverable_type==='CL'?'GC Clarification':'RFI'}</td><td>{x.system_name}</td><td><b>{x.title}</b><small>{renderRefSlr(x.related_master_finding_id)}</small></td><td>{x.content}</td><td>{x.reference||'—'}</td><td>{x.status}</td><td>{x.response||'—'}</td><td className={styles.noPrint}><button onClick={()=>openEditAction(x)}>Edit</button></td></tr>)}</tbody></table></section>:null}

   {tab==='checklist'?<section className={styles.workspace}><Header eyebrow="CLIENT / BIDDER DELIVERABLE" title="Contractor Scope Confirmation Checklist" subtitle="Separate from CL numbering. Project-specific confirmations use CSC-###." action="Add Confirmation" onAction={openNewChecklist}/><DocumentHeader title="Contractor Scope Confirmation Checklist" project={projectTitle} revision={master.revision} date={today}/><table className={styles.table}><thead><tr><th>ID</th><th>Category</th><th>System</th><th>Contractor Confirmation</th><th>Response</th><th>Contractor Notes</th><th className={styles.noPrint}>Edit</th></tr></thead><tbody>{checklist.map(x=><tr key={x.id}><td><b>{x.display_number}</b></td><td>{x.category}</td><td>{x.system_name}</td><td><b>{x.question}</b><small>{renderRefSlr(x.linked_master_finding_id)}</small></td><td>{x.response||'Yes / No / Qualified'}</td><td>{x.response_reason||''}</td><td className={styles.noPrint}><button onClick={()=>openEditChecklist(x)}>Edit</button></td></tr>)}</tbody></table></section>:null}

   {tab==='ve'?<section className={styles.workspace}><Header eyebrow="CLIENT DELIVERABLE" title="VE Opportunity Log" subtitle="Optional departures from the compliant Base Bid. Pricing is documented only when supplied by a bidder/GC/vendor." action="Add VE" onAction={()=>openNewAction('VE')}/><DocumentHeader title="VE Opportunity Log" project={projectTitle} revision={master.revision} date={today}/><div className={styles.cards}>{byType('VE').filter(x=>x.client_facing).map(x=><article className={styles.card} key={x.id}><div className={styles.cardTitle}><div><span>{x.display_number} · {x.system_name}</span><h3>{x.title}</h3></div><Badge tone={x.status==='Accepted'?'green':x.status==='Rejected'?'red':x.status==='Under Review'?'amber':'blue'}>{x.status}</Badge></div><dl><div><dt>VE Opportunity</dt><dd>{x.content}</dd></div><div><dt>Potential Impact / Considerations</dt><dd>{x.impact_considerations||'—'}</dd></div><div><dt>References</dt><dd>{x.reference||'—'}</dd></div><div><dt>Related SLR</dt><dd>{renderRefSlr(x.related_master_finding_id)}</dd></div></dl><div className={styles.noPrint}><button onClick={()=>openEditAction(x)}>Edit</button></div></article>)}</div></section>:null}

   {tab==='bid-internal'?<section className={styles.workspace}><Header eyebrow="INTERNAL WORKSPACE" title="Bid Alignment — Internal" subtitle="Record documented proposal scope, qualifications, and bidder/GC-supplied adders or credits. No ScopeLogic-generated budget pricing." action="Add Bid Item" onAction={openNewBid}/><table className={styles.table}><thead><tr><th>Bidder</th><th>Scope Item</th><th>RBB / Source</th><th>Proposal Status</th><th>Proposal Reference</th><th>Clarification</th><th>Documented Adjustment</th><th>Pricing Source</th><th className={styles.noPrint}>Edit</th></tr></thead><tbody>{bids.map(x=>{const rel=x.related_deliverable_id?actionMap.get(x.related_deliverable_id):null;const amt=x.documented_adjustment==null?'Unpriced':`${x.adjustment_type==='Deduct'?'-':x.adjustment_type==='Add'?'+':''}$${Number(x.documented_adjustment).toLocaleString()}`;return <tr key={x.id}><td><b>{x.bidder_name}</b></td><td>{x.scope_item}</td><td>{rel?.display_number||'—'}</td><td>{x.proposal_status}</td><td>{x.proposal_reference||'—'}</td><td>{x.clarification||'—'}</td><td>{amt}</td><td>{x.pricing_source||'—'}</td><td className={styles.noPrint}><button onClick={()=>openEditBid(x)}>Edit</button></td></tr>})}</tbody></table></section>:null}

   {tab==='bid-report'?<section className={styles.workspace}><Header eyebrow="CLIENT DELIVERABLE" title="ScopeLogic Bid Alignment Report" subtitle="External comparison based on documented bidder scope and documented adders/credits only."/><DocumentHeader title="ScopeLogic Bid Alignment Report" project={projectTitle} revision={master.revision} date={today}/><table className={styles.table}><thead><tr><th>Bidder</th><th>Scope Item</th><th>RBB / Source</th><th>Alignment</th><th>Documented Adjustment</th><th>Client Note</th></tr></thead><tbody>{bids.map(x=>{const rel=x.related_deliverable_id?actionMap.get(x.related_deliverable_id):null;const amt=x.documented_adjustment==null?'Unpriced':`${x.adjustment_type==='Deduct'?'-':x.adjustment_type==='Add'?'+':''}$${Number(x.documented_adjustment).toLocaleString()}`;return <tr key={x.id}><td><b>{x.bidder_name}</b></td><td>{x.scope_item}</td><td>{rel?.display_number||'—'}</td><td>{x.proposal_status}</td><td>{amt}</td><td>{x.client_notes||'—'}</td></tr>})}</tbody></table></section>:null}

   {tab==='internal'?<section className={styles.workspace}><Header eyebrow="INTERNAL ONLY" title="SLR Action Register" subtitle="All downstream actions linked to the originating SLR. ScopeLogic Clarifications (SLC) remain internal." action="Add Internal Clarification" onAction={()=>openNewAction('SLC')}/><table className={styles.table}><thead><tr><th>ID</th><th>Type</th><th>Related SLR</th><th>System</th><th>Title</th><th>Content</th><th>Status</th><th>Client Facing</th><th className={styles.noPrint}>Edit</th></tr></thead><tbody>{actions.sort((a,b)=>a.sort_order-b.sort_order).map(x=><tr key={x.id}><td><b>{x.display_number}</b></td><td>{x.deliverable_type}</td><td>{renderRefSlr(x.related_master_finding_id)}</td><td>{x.system_name}</td><td>{x.title}</td><td>{x.content}</td><td>{x.status}</td><td>{x.client_facing?'Yes':'No'}</td><td className={styles.noPrint}><button onClick={()=>openEditAction(x)}>Edit</button></td></tr>)}</tbody></table></section>:null}
  </section>

  {showAction?<Modal title={editingAction?`Edit ${editingAction.display_number}`:`Add ${actionDraft.deliverable_type}`} close={()=>setShowAction(false)} save={()=>void saveAction()} deleteAction={editingAction?()=>void deleteAction(editingAction):undefined}><label>Type<select value={actionDraft.deliverable_type} disabled={!!editingAction} onChange={e=>setActionDraft({...blankAction(e.target.value as ActionType)})}>{['RBB','CL','RFI','VE','SLC'].map(x=><option key={x}>{x}</option>)}</select></label><label>Related SLR<select value={actionDraft.related_master_finding_id||''} onChange={e=>{const id=e.target.value||null;const f=id?findingMap.get(id):null;setActionDraft(d=>({...d,related_master_finding_id:id,system_name:f?.systems?.[0]||d.system_name,title:d.title||f?.scope_item||''}))}}><option value="">None</option>{findings.map(f=><option key={f.id} value={f.id}>{f.display_number} — {f.scope_item}</option>)}</select></label><label>System<input value={actionDraft.system_name} onChange={e=>setActionDraft(d=>({...d,system_name:e.target.value}))}/></label><label>Title / Scope Item<input value={actionDraft.title} onChange={e=>setActionDraft(d=>({...d,title:e.target.value}))}/></label><label>{actionDraft.deliverable_type==='VE'?'VE Opportunity':actionDraft.deliverable_type==='RBB'?'Recommended Base Bid':actionDraft.deliverable_type==='RFI'?'RFI Question':actionDraft.deliverable_type==='CL'?'GC Clarification':'ScopeLogic Clarification'}<textarea rows={5} value={actionDraft.content} onChange={e=>setActionDraft(d=>({...d,content:e.target.value}))}/></label>{actionDraft.deliverable_type==='VE'?<label>Potential Impact / Considerations<textarea rows={4} value={actionDraft.impact_considerations} onChange={e=>setActionDraft(d=>({...d,impact_considerations:e.target.value}))}/></label>:null}<label>References<textarea rows={2} value={actionDraft.reference} onChange={e=>setActionDraft(d=>({...d,reference:e.target.value}))}/></label><div className={styles.formRow}><label>Status<input value={actionDraft.status} onChange={e=>setActionDraft(d=>({...d,status:e.target.value}))}/></label><label className={styles.check}><input type="checkbox" checked={actionDraft.client_facing} onChange={e=>setActionDraft(d=>({...d,client_facing:e.target.checked}))}/> Client Facing</label></div>{['CL','RFI'].includes(actionDraft.deliverable_type)?<><label>Response<textarea rows={3} value={actionDraft.response} onChange={e=>setActionDraft(d=>({...d,response:e.target.value}))}/></label><div className={styles.formRow}><label>Response Date<input type="date" value={actionDraft.response_date||''} onChange={e=>setActionDraft(d=>({...d,response_date:e.target.value||null}))}/></label><label>Response Source<input value={actionDraft.response_source} onChange={e=>setActionDraft(d=>({...d,response_source:e.target.value}))}/></label></div></>:null}</Modal>:null}

  {showChecklist?<Modal title={editingChecklist?`Edit ${editingChecklist.display_number}`:'Add Contractor Confirmation'} close={()=>setShowChecklist(false)} save={()=>void saveChecklist()} deleteAction={editingChecklist?()=>void deleteChecklist(editingChecklist):undefined}><label>Related SLR<select value={checkDraft.linked_master_finding_id||''} onChange={e=>{const id=e.target.value||null;const f=id?findingMap.get(id):null;setCheckDraft(d=>({...d,linked_master_finding_id:id,system_name:f?.systems?.[0]||d.system_name}))}}><option value="">None</option>{findings.map(f=><option key={f.id} value={f.id}>{f.display_number} — {f.scope_item}</option>)}</select></label><div className={styles.formRow}><label>Category<input value={checkDraft.category} onChange={e=>setCheckDraft(d=>({...d,category:e.target.value}))}/></label><label>System<input value={checkDraft.system_name} onChange={e=>setCheckDraft(d=>({...d,system_name:e.target.value}))}/></label></div><label>Contractor Confirmation<textarea rows={4} value={checkDraft.question} onChange={e=>setCheckDraft(d=>({...d,question:e.target.value}))}/></label><div className={styles.formRow}><label>Status<input value={checkDraft.status} onChange={e=>setCheckDraft(d=>({...d,status:e.target.value}))}/></label><label>Response<input value={checkDraft.response} onChange={e=>setCheckDraft(d=>({...d,response:e.target.value}))}/></label></div><label>Contractor Notes<textarea rows={3} value={checkDraft.response_reason} onChange={e=>setCheckDraft(d=>({...d,response_reason:e.target.value}))}/></label></Modal>:null}

  {showNote?<Modal title="Add Review Note" close={()=>setShowNote(false)} save={()=>void saveNote()}><div className={styles.formRow}><label>System<input value={noteDraft.system_name} onChange={e=>setNoteDraft(d=>({...d,system_name:e.target.value}))}/></label><label>Source Type<select value={noteDraft.source_type} onChange={e=>setNoteDraft(d=>({...d,source_type:e.target.value}))}>{['Specification','Drawing','Addendum','Narrative','Meeting','Field','Other'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Topic<input value={noteDraft.topic} onChange={e=>setNoteDraft(d=>({...d,topic:e.target.value}))}/></label><label>Source Reference<input value={noteDraft.source_reference} onChange={e=>setNoteDraft(d=>({...d,source_reference:e.target.value}))}/></label><label>Observation<textarea rows={5} value={noteDraft.observation} onChange={e=>setNoteDraft(d=>({...d,observation:e.target.value}))}/></label><label>Related SLR<select value={noteDraft.linked_master_finding_id||''} onChange={e=>setNoteDraft(d=>({...d,linked_master_finding_id:e.target.value||null,disposition:e.target.value?'Linked to SLR':d.disposition}))}><option value="">None</option>{findings.map(f=><option key={f.id} value={f.id}>{f.display_number} — {f.scope_item}</option>)}</select></label></Modal>:null}

  {showBid?<Modal title={editingBid?'Edit Bid Alignment Item':'Add Bid Alignment Item'} close={()=>setShowBid(false)} save={()=>void saveBid()} deleteAction={editingBid?()=>void deleteBid(editingBid):undefined}><div className={styles.formRow}><label>Bidder<input value={bidDraft.bidder_name} onChange={e=>setBidDraft(d=>({...d,bidder_name:e.target.value}))}/></label><label>Proposal Status<select value={bidDraft.proposal_status} onChange={e=>setBidDraft(d=>({...d,proposal_status:e.target.value}))}>{['Included','Excluded','Qualified','Unclear'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Scope Item<input value={bidDraft.scope_item} onChange={e=>setBidDraft(d=>({...d,scope_item:e.target.value}))}/></label><label>Related RBB / Source<select value={bidDraft.related_deliverable_id||''} onChange={e=>setBidDraft(d=>({...d,related_deliverable_id:e.target.value||null}))}><option value="">None</option>{byType('RBB').map(x=><option key={x.id} value={x.id}>{x.display_number} — {x.title}</option>)}</select></label><label>Proposal Reference<input value={bidDraft.proposal_reference} onChange={e=>setBidDraft(d=>({...d,proposal_reference:e.target.value}))}/></label><label>Clarification<textarea rows={3} value={bidDraft.clarification} onChange={e=>setBidDraft(d=>({...d,clarification:e.target.value}))}/></label><div className={styles.formRow}><label>Documented Adjustment<input type="number" value={bidDraft.documented_adjustment} onChange={e=>setBidDraft(d=>({...d,documented_adjustment:e.target.value}))}/></label><label>Adjustment Type<select value={bidDraft.adjustment_type} onChange={e=>setBidDraft(d=>({...d,adjustment_type:e.target.value}))}>{['None','Add','Deduct'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Pricing Source<input value={bidDraft.pricing_source} onChange={e=>setBidDraft(d=>({...d,pricing_source:e.target.value}))}/></label><label>Internal Notes<textarea rows={3} value={bidDraft.internal_notes} onChange={e=>setBidDraft(d=>({...d,internal_notes:e.target.value}))}/></label><label>Client Note<textarea rows={3} value={bidDraft.client_notes} onChange={e=>setBidDraft(d=>({...d,client_notes:e.target.value}))}/></label></Modal>:null}
 </main>
}

function Header({eyebrow,title,subtitle,action,onAction}:{eyebrow:string;title:string;subtitle:string;action?:string;onAction?:()=>void}){return <div className={styles.workspaceHead}><div><span>{eyebrow}</span><h2>{title}</h2><p>{subtitle}</p></div>{action&&onAction?<button className={styles.primary} onClick={onAction}>{action}</button>:null}</div>}
function DocumentHeader({title,project,revision,date}:{title:string;project:string;revision:string;date:string}){return <div className={styles.documentHeader}><img src="/brand/scopelogic-wordmark.png" alt="ScopeLogic"/><div><b>{title}</b><span>{project}</span><span>{revision} · {date}</span></div></div>}
function Empty({text}:{text:string}){return <div className={styles.empty}>{text}</div>}
function Modal({title,children,close,save,deleteAction}:{title:string;children:React.ReactNode;close:()=>void;save:()=>void;deleteAction?:()=>void}){return <div className={styles.modalBackdrop}><section className={styles.modal}><header><h2>{title}</h2><button onClick={close}>×</button></header><div className={styles.form}>{children}</div><footer>{deleteAction?<button className={styles.danger} onClick={deleteAction}>Delete</button>:<span/>}<div><button onClick={close}>Cancel</button><button className={styles.primary} onClick={save}>Save</button></div></footer></section></div>}
