'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { createClient } from '../lib/supabase/client';
import { DEMO_MASTER_ID } from '../lib/demo/config';
import styles from './demo-workflow-panels.module.css';

type ActionType = 'RBB' | 'CL' | 'RFI' | 'VE';
type Tab = 'rbb' | 'cl' | 'rfi' | 've' | 'checklist' | 'bid' | 'reports';
type Action = { id:string; related_master_finding_id:string|null; deliverable_type:string; sequence_number:number; display_number:string; system_name:string; title:string; content:string; reference:string; status:string; response:string; impact_considerations:string };
type Finding = { id:string; display_number:string; scope_item:string; systems:string[]; status:string };
type Checklist = { id:string; linked_master_finding_id:string|null; sequence_number:number; display_number:string; category:string; system_name:string; question:string; status:string; response:string; response_reason:string };
type Bid = { id:string; related_deliverable_id:string|null; bidder_name:string; scope_item:string; proposal_status:string; proposal_reference:string; clarification:string; documented_adjustment:number|null; client_notes:string };
type Props = { onOpenReleases?: () => void; onOpenSlr?: () => void };
const pad=(n:number)=>String(n).padStart(3,'0');
const tabLabels: Record<Tab,string>={rbb:'Recommended Base Bid',cl:'GC Clarifications',rfi:'Formal RFIs',ve:'VE Opportunities',checklist:'Contractor Confirmation',bid:'Bid Alignment',reports:'Reports / Releases'};
const systems=['Structured Cabling','CCTV','Access Control','Audio Visual','Paging','Other'];

export default function DemoDeliverablesHub({onOpenReleases,onOpenSlr}:Props){
 const supabase=useMemo(()=>createClient(),[]);
 const [tab,setTab]=useState<Tab>('rbb');
 const [findings,setFindings]=useState<Finding[]>([]);const [actions,setActions]=useState<Action[]>([]);const [checklist,setChecklist]=useState<Checklist[]>([]);const [bids,setBids]=useState<Bid[]>([]);
 const [message,setMessage]=useState('');const [error,setError]=useState('');const [editing,setEditing]=useState(false);
 const [actionDraft,setActionDraft]=useState({related_master_finding_id:'',system_name:'Structured Cabling',title:'',content:'',reference:'',status:'Open',impact_considerations:''});
 const [checkDraft,setCheckDraft]=useState({linked_master_finding_id:'',category:'Project-Specific',system_name:'Structured Cabling',question:'',status:'Open',response:'',response_reason:''});
 const [bidDraft,setBidDraft]=useState({related_deliverable_id:'',bidder_name:'',scope_item:'',proposal_status:'Unclear',proposal_reference:'',clarification:'',client_notes:''});
 const load=useCallback(async()=>{const [f,a,c,b]=await Promise.all([
   supabase.from('master_project_findings').select('*').eq('master_project_id',DEMO_MASTER_ID).order('sequence_number'),
   supabase.from('master_project_deliverable_items').select('*').eq('master_project_id',DEMO_MASTER_ID).order('deliverable_type').order('sequence_number'),
   supabase.from('master_project_checklist_items').select('*').eq('master_project_id',DEMO_MASTER_ID).order('sequence_number'),
   supabase.from('master_project_bid_alignment_items').select('*').eq('master_project_id',DEMO_MASTER_ID).order('bidder_name').order('sort_order')
 ]);const failure=f.error||a.error||c.error||b.error;if(failure){setError(failure.message);return;}setFindings((f.data||[]) as Finding[]);setActions((a.data||[]) as Action[]);setChecklist((c.data||[]) as Checklist[]);setBids((b.data||[]) as Bid[]);},[supabase]);
 useEffect(()=>{void load();},[load]);
 const findingMap=useMemo(()=>new Map(findings.map((item)=>[item.id,item])),[findings]);
 const related=(id:string|null|undefined)=>id&&findingMap.get(id)?`${findingMap.get(id)!.display_number} — ${findingMap.get(id)!.scope_item}`:'—';
 const actionType:ActionType=tab==='rbb'?'RBB':tab==='cl'?'CL':tab==='rfi'?'RFI':'VE';
 const actionRows=actions.filter((item)=>item.deliverable_type===actionType).sort((a,b)=>a.sequence_number-b.sequence_number);
 const resetEditors=()=>{setEditing(false);setActionDraft({related_master_finding_id:'',system_name:'Structured Cabling',title:'',content:'',reference:'',status:'Open',impact_considerations:''});setCheckDraft({linked_master_finding_id:'',category:'Project-Specific',system_name:'Structured Cabling',question:'',status:'Open',response:'',response_reason:''});setBidDraft({related_deliverable_id:'',bidder_name:'',scope_item:'',proposal_status:'Unclear',proposal_reference:'',clarification:'',client_notes:''});};
 const saveAction=async()=>{if(!actionDraft.title.trim()||!actionDraft.content.trim()){setError('Title and deliverable content are required.');return;}const seq=Math.max(0,...actions.filter((item)=>item.deliverable_type===actionType).map((item)=>item.sequence_number))+1;const result=await supabase.from('master_project_deliverable_items').insert({owner_id:'demo-presenter',master_project_id:DEMO_MASTER_ID,created_by_user_id:'demo-presenter',related_master_finding_id:actionDraft.related_master_finding_id||null,deliverable_type:actionType,sequence_number:seq,display_number:`${actionType}-${pad(seq)}`,system_name:actionDraft.system_name,title:actionDraft.title.trim(),content:actionDraft.content.trim(),impact_considerations:actionDraft.impact_considerations.trim(),reference:actionDraft.reference.trim(),status:actionType==='RBB'?'Current':actionType==='VE'?'Identified':actionDraft.status,response:'',response_date:null,response_source:'',client_facing:true,sort_order:seq});if(result.error){setError(result.error.message);return;}setMessage(`${actionType}-${pad(seq)} added to Deliverables.`);resetEditors();await load();};
 const saveChecklist=async()=>{if(!checkDraft.question.trim()){setError('Contractor confirmation text is required.');return;}const seq=Math.max(0,...checklist.map((item)=>item.sequence_number))+1;const result=await supabase.from('master_project_checklist_items').insert({owner_id:'demo-presenter',master_project_id:DEMO_MASTER_ID,created_by_user_id:'demo-presenter',linked_master_finding_id:checkDraft.linked_master_finding_id||null,sequence_number:seq,display_number:`CSC-${pad(seq)}`,sort_order:seq,category:checkDraft.category,system_name:checkDraft.system_name,question:checkDraft.question.trim(),status:checkDraft.status,response:checkDraft.response.trim(),response_reason:checkDraft.response_reason.trim()});if(result.error){setError(result.error.message);return;}setMessage(`CSC-${pad(seq)} added.`);resetEditors();await load();};
 const saveBid=async()=>{if(!bidDraft.bidder_name.trim()||!bidDraft.scope_item.trim()){setError('Bidder and scope item are required.');return;}const result=await supabase.from('master_project_bid_alignment_items').insert({owner_id:'demo-presenter',master_project_id:DEMO_MASTER_ID,created_by_user_id:'demo-presenter',related_deliverable_id:bidDraft.related_deliverable_id||null,bidder_name:bidDraft.bidder_name.trim(),scope_item:bidDraft.scope_item.trim(),proposal_status:bidDraft.proposal_status,proposal_reference:bidDraft.proposal_reference.trim(),clarification:bidDraft.clarification.trim(),documented_adjustment:null,adjustment_type:'None',pricing_source:'',internal_notes:'Demonstration comparison only',client_notes:bidDraft.client_notes.trim(),sort_order:bids.length+1});if(result.error){setError(result.error.message);return;}setMessage('Bid alignment item added.');resetEditors();await load();};
 const openEditor=()=>{setError('');setMessage('');setEditing(true);};
 return <section className={styles.panel} aria-label="Deliverables">
   <div className={styles.panelHeader}><div><span className={styles.eyebrow}>DELIVERABLES</span><h2>Project Deliverables</h2><p>All downstream scope outputs live in one workspace. SLRs remain the parent findings; deliverables are the actions and reports they drive.</p></div>{onOpenSlr&&<button className={styles.button} onClick={onOpenSlr}>Open SLR Matrix</button>}</div>
   <div className={styles.tabs}>{(Object.keys(tabLabels) as Tab[]).map((id)=><button key={id} className={tab===id?styles.active:''} onClick={()=>{setTab(id);resetEditors();setMessage('');setError('');}}>{tabLabels[id]}</button>)}</div>
   <div className={styles.body}>{message&&<div className={styles.message}>{message}</div>}{error&&<div className={styles.error}>{error}</div>}
   {(['rbb','cl','rfi','ve'] as Tab[]).includes(tab)&&<>
     <div className={styles.toolbar}><div><h3>{tabLabels[tab]}</h3><span>{actionRows.length} items</span></div><button className={`${styles.button} ${styles.primary}`} onClick={openEditor}>+ Add {actionType}</button></div>
     {editing&&<div className={styles.editor}><label>Related SLR<select value={actionDraft.related_master_finding_id} onChange={(e)=>setActionDraft({...actionDraft,related_master_finding_id:e.target.value})}><option value="">Unlinked</option>{findings.map((f)=><option key={f.id} value={f.id}>{f.display_number} — {f.scope_item}</option>)}</select></label><label>System<select value={actionDraft.system_name} onChange={(e)=>setActionDraft({...actionDraft,system_name:e.target.value})}>{systems.map((s)=><option key={s}>{s}</option>)}</select></label><label className={styles.full}>Title<input value={actionDraft.title} onChange={(e)=>setActionDraft({...actionDraft,title:e.target.value})}/></label><label className={styles.full}>{actionType==='RFI'?'Question':actionType==='RBB'?'Recommended Base Bid':actionType==='VE'?'VE Description':'Clarification'}<textarea value={actionDraft.content} onChange={(e)=>setActionDraft({...actionDraft,content:e.target.value})}/></label><label className={styles.full}>Source Reference<input value={actionDraft.reference} onChange={(e)=>setActionDraft({...actionDraft,reference:e.target.value})}/></label>{actionType==='VE'&&<label className={styles.full}>Impact / Conditions<textarea value={actionDraft.impact_considerations} onChange={(e)=>setActionDraft({...actionDraft,impact_considerations:e.target.value})}/></label>}<div className={styles.formActions}><button className={styles.button} onClick={resetEditors}>Cancel</button><button className={`${styles.button} ${styles.primary}`} onClick={()=>void saveAction()}>Save {actionType}</button></div></div>}
     <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>ID</th><th>System</th><th>Subject</th><th>{actionType==='RFI'?'Question':actionType==='RBB'?'Recommended Base Bid':actionType==='VE'?'VE Opportunity':'Clarification'}</th><th>Reference</th><th>Related SLR</th><th>Status</th></tr></thead><tbody>{actionRows.map((row)=><tr key={row.id}><td><b>{row.display_number}</b></td><td>{row.system_name}</td><td>{row.title}</td><td>{row.content}{row.impact_considerations?<small>{row.impact_considerations}</small>:null}</td><td>{row.reference||'—'}</td><td>{related(row.related_master_finding_id)}</td><td>{row.status}</td></tr>)}</tbody></table></div>
   </>}
   {tab==='checklist'&&<><div className={styles.toolbar}><div><h3>Contractor Scope Confirmation</h3><span>{checklist.length} items</span></div><button className={`${styles.button} ${styles.primary}`} onClick={openEditor}>+ Add CSC</button></div>{editing&&<div className={styles.editor}><label>Related SLR<select value={checkDraft.linked_master_finding_id} onChange={(e)=>setCheckDraft({...checkDraft,linked_master_finding_id:e.target.value})}><option value="">Unlinked</option>{findings.map((f)=><option key={f.id} value={f.id}>{f.display_number} — {f.scope_item}</option>)}</select></label><label>System<select value={checkDraft.system_name} onChange={(e)=>setCheckDraft({...checkDraft,system_name:e.target.value})}>{systems.map((s)=><option key={s}>{s}</option>)}</select></label><label className={styles.full}>Confirmation Requirement<textarea value={checkDraft.question} onChange={(e)=>setCheckDraft({...checkDraft,question:e.target.value})}/></label><label>Response<input value={checkDraft.response} onChange={(e)=>setCheckDraft({...checkDraft,response:e.target.value})}/></label><label>Reason / Qualification<input value={checkDraft.response_reason} onChange={(e)=>setCheckDraft({...checkDraft,response_reason:e.target.value})}/></label><div className={styles.formActions}><button className={styles.button} onClick={resetEditors}>Cancel</button><button className={`${styles.button} ${styles.primary}`} onClick={()=>void saveChecklist()}>Save CSC</button></div></div>}<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>ID</th><th>System</th><th>Confirmation</th><th>Related SLR</th><th>Status</th><th>Response</th><th>Reason</th></tr></thead><tbody>{checklist.map((row)=><tr key={row.id}><td><b>{row.display_number}</b></td><td>{row.system_name}</td><td>{row.question}</td><td>{related(row.linked_master_finding_id)}</td><td>{row.status}</td><td>{row.response||'—'}</td><td>{row.response_reason||'—'}</td></tr>)}</tbody></table></div></>}
   {tab==='bid'&&<><div className={styles.toolbar}><div><h3>Bid Alignment</h3><span>{bids.length} comparison rows</span></div><button className={`${styles.button} ${styles.primary}`} onClick={openEditor}>+ Add Comparison</button></div>{editing&&<div className={styles.editor}><label>Bidder<input value={bidDraft.bidder_name} onChange={(e)=>setBidDraft({...bidDraft,bidder_name:e.target.value})}/></label><label>Status<select value={bidDraft.proposal_status} onChange={(e)=>setBidDraft({...bidDraft,proposal_status:e.target.value})}><option>Included</option><option>Excluded</option><option>Qualified</option><option>Unclear</option></select></label><label className={styles.full}>Scope Item<input value={bidDraft.scope_item} onChange={(e)=>setBidDraft({...bidDraft,scope_item:e.target.value})}/></label><label>Proposal Reference<input value={bidDraft.proposal_reference} onChange={(e)=>setBidDraft({...bidDraft,proposal_reference:e.target.value})}/></label><label>Clarification<input value={bidDraft.clarification} onChange={(e)=>setBidDraft({...bidDraft,clarification:e.target.value})}/></label><label className={styles.full}>Client Note<textarea value={bidDraft.client_notes} onChange={(e)=>setBidDraft({...bidDraft,client_notes:e.target.value})}/></label><div className={styles.formActions}><button className={styles.button} onClick={resetEditors}>Cancel</button><button className={`${styles.button} ${styles.primary}`} onClick={()=>void saveBid()}>Save Comparison</button></div></div>}<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Bidder</th><th>Scope Item</th><th>Status</th><th>Proposal Reference</th><th>Clarification</th><th>Client Note</th></tr></thead><tbody>{bids.map((row)=><tr key={row.id}><td><b>{row.bidder_name}</b></td><td>{row.scope_item}</td><td>{row.proposal_status}</td><td>{row.proposal_reference||'—'}</td><td>{row.clarification||'—'}</td><td>{row.client_notes||'—'}</td></tr>)}</tbody></table></div></>}
   {tab==='reports'&&<div className={styles.reportCards}><div className={styles.reportCard}><b>Scope / Bid Basis Package</b><p>Recommended Base Bid, GC Clarifications, RFIs, VE, and Contractor Confirmation are maintained in the tabs above and issued together as required.</p></div><div className={styles.reportCard}><b>Bid Alignment Report</b><p>Use the Bid Alignment tab to normalize bidder inclusions, exclusions and qualifications before procurement decisions.</p></div><div className={styles.reportCard}><b>Official Releases</b><p>Create and archive customer-facing releases after the deliverables are reviewed.</p>{onOpenReleases&&<button className={`${styles.button} ${styles.primary}`} onClick={onOpenReleases}>Open Official Releases</button>}</div></div>}
   </div>
 </section>;
}
