'use client';

import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { demoSlrTemplateRecords, type DemoSlrTemplateRecord as TemplateRecord } from '../lib/demo/slr-template-library';

type ActionFilter='All'|'RBB'|'GC Clarification'|'Formal RFI'|'Checklist';
const text=(v:unknown)=>String(v??'').trim();const lower=(v:unknown)=>text(v).toLowerCase();
function systemsFor(r:TemplateRecord){const d=r.template_data||{};const s=Array.isArray(d.systems)?d.systems.map(text).filter(Boolean):[];if(!s.length&&d.system)s.push(text(d.system));return Array.from(new Set(s));}
function actionsFor(r:TemplateRecord){const d=r.template_data||{};const a:string[]=[];if(d.sow||(d.recommendations&&Object.values(d.recommendations).some(text)))a.push('RBB');if(d.clarification)a.push('GC Clarification');if(d.formalRfi||(Array.isArray(d.rfis)&&d.rfis.length))a.push('Formal RFI');if(d.checklist||text(d.checklistItem)||(d.checklistItems&&Object.values(d.checklistItems).some(text)))a.push('Checklist');return a;}
function searchableText(r:TemplateRecord){const d=r.template_data||{};return[r.name,d.title,d.system,...(Array.isArray(d.systems)?d.systems:[]),d.concern,d.basis,d.rfiQuestion,d.reference,d.sourceType,d.checklistItem,JSON.stringify(d.recommendations||{}),JSON.stringify(d.checklistItems||{})].map(lower).join(' ');}

export default function SlrTemplateSearchEnhancer(){
 const [mount,setMount]=useState<HTMLElement|null>(null),[nativeSelect,setNativeSelect]=useState<HTMLSelectElement|null>(null),[query,setQuery]=useState(''),[system,setSystem]=useState('All'),[action,setAction]=useState<ActionFilter>('All'),[selected,setSelected]=useState('');
 const [quoteMount,setQuoteMount]=useState<HTMLElement|null>(null),[quoteList,setQuoteList]=useState<HTMLElement|null>(null),[quoteQuery,setQuoteQuery]=useState(''),[quoteSystem,setQuoteSystem]=useState('All'),[quoteSystems,setQuoteSystems]=useState<string[]>([]),[quoteVisibleCount,setQuoteVisibleCount]=useState(0),[quoteTotalCount,setQuoteTotalCount]=useState(0);
 const [ruleMount,setRuleMount]=useState<HTMLElement|null>(null),[ruleSelect,setRuleSelect]=useState<HTMLSelectElement|null>(null),[ruleQuery,setRuleQuery]=useState(''),[ruleSystem,setRuleSystem]=useState('All'),[ruleSystems,setRuleSystems]=useState<string[]>([]),[ruleVisibleCount,setRuleVisibleCount]=useState(0),[ruleTotalCount,setRuleTotalCount]=useState(0);
 useEffect(()=>{let o:MutationObserver|null=null;const attach=()=>{const bar=document.querySelector<HTMLElement>('.template-library'),sel=bar?.querySelector<HTMLSelectElement>('select');if(!bar||!sel)return false;let host=bar.querySelector<HTMLElement>('[data-slr-template-search-host]');if(!host){host=document.createElement('div');host.dataset.slrTemplateSearchHost='true';sel.before(host)}bar.classList.add('template-library-search-enabled');setMount(host);setNativeSelect(sel);setSelected(sel.value);sel.addEventListener('change',()=>setSelected(sel.value));return true};if(!attach()){o=new MutationObserver(()=>{if(attach())o?.disconnect()});o.observe(document.body,{childList:true,subtree:true})}return()=>o?.disconnect()},[]);
 useEffect(()=>{let body:MutationObserver|null=null,listObs:MutationObserver|null=null;const attach=()=>{const list=Array.from(document.querySelectorAll<HTMLElement>('.quote-list')).find(x=>lower(x.querySelector('button.primary')?.textContent).includes('new template'));if(!list)return false;let host=list.querySelector<HTMLElement>('[data-quote-template-search-host]');if(!host){host=document.createElement('div');host.dataset.quoteTemplateSearchHost='true';list.querySelector('button.primary')?.after(host)}list.classList.add('quote-template-list-search-enabled');setQuoteMount(host);setQuoteList(list);const refresh=()=>{const vals=Array.from(list.querySelectorAll<HTMLButtonElement>(':scope > button:not(.primary)')).map(b=>text(b.querySelector('small')?.textContent)).filter(v=>v&&v!=='NEW DRAFT');setQuoteSystems(Array.from(new Set(vals)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})))};refresh();listObs=new MutationObserver(refresh);listObs.observe(list,{childList:true,subtree:true,characterData:true});return true};if(!attach()){body=new MutationObserver(()=>{if(attach())body?.disconnect()});body.observe(document.body,{childList:true,subtree:true})}return()=>{body?.disconnect();listObs?.disconnect()}},[]);
 useEffect(()=>{let body:MutationObserver|null=null;const attach=()=>{const panel=document.querySelector<HTMLElement>('.compact-rule-library'),sel=panel?.querySelector<HTMLSelectElement>('.rule-library-select select');if(!panel||!sel)return false;let host=panel.querySelector<HTMLElement>('[data-takeoff-rule-search-host]');if(!host){host=document.createElement('div');host.dataset.takeoffRuleSearchHost='true';panel.querySelector('.rule-library-select')?.before(host)}panel.classList.add('takeoff-rule-search-enabled');setRuleMount(host);setRuleSelect(sel);const opts=Array.from(sel.options).filter(o=>o.value),systems=opts.map(o=>text(o.textContent).split(' — ')[0]).filter(Boolean);setRuleSystems(Array.from(new Set(systems)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})));return true};if(!attach()){body=new MutationObserver(()=>{if(attach())body?.disconnect()});body.observe(document.body,{childList:true,subtree:true})}return()=>body?.disconnect()},[]);
 useEffect(()=>{if(!quoteList)return;const bs=Array.from(quoteList.querySelectorAll<HTMLButtonElement>(':scope > button:not(.primary)')),needle=lower(quoteQuery),searching=Boolean(needle||quoteSystem!=='All');let n=0;for(const [index,b] of bs.entries()){const s=text(b.querySelector('small')?.textContent),matches=(!needle||lower(b.textContent).includes(needle))&&(quoteSystem==='All'||s===quoteSystem),ok=searching?matches:index<5;b.hidden=!ok;if(ok)n++}setQuoteTotalCount(bs.length);setQuoteVisibleCount(n)},[quoteList,quoteQuery,quoteSystem,quoteSystems]);
 useEffect(()=>{if(!ruleSelect)return;const opts=Array.from(ruleSelect.options).filter(o=>o.value),needle=lower(ruleQuery),searching=Boolean(needle||ruleSystem!=='All');let n=0;for(const [index,o] of opts.entries()){const label=text(o.textContent),s=label.split(' — ')[0],matches=(!needle||lower(label).includes(needle))&&(ruleSystem==='All'||s===ruleSystem),ok=searching?matches:index<5;o.hidden=!ok;if(ok)n++}setRuleTotalCount(opts.length);setRuleVisibleCount(n);const selectedOption=opts.find(o=>o.value===ruleSelect.value);if(selectedOption?.hidden){ruleSelect.value='';ruleSelect.dispatchEvent(new Event('change',{bubbles:true}))}},[ruleSelect,ruleQuery,ruleSystem,ruleSystems]);
 const records=demoSlrTemplateRecords,systems=useMemo(()=>Array.from(new Set(records.flatMap(systemsFor))).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[records]);const searching=Boolean(query.trim()||system!=='All'||action!=='All');const visible=useMemo(()=>{if(!searching)return[];const needle=lower(query);return records.filter(r=>(system==='All'||systemsFor(r).includes(system))&&(action==='All'||actionsFor(r).includes(action))&&(!needle||searchableText(r).includes(needle))).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}))},[records,query,system,action,searching]);const recent=records.slice(0,5);
 const choose=(r:TemplateRecord)=>{if(!nativeSelect)return;const o=Array.from(nativeSelect.options).find(x=>x.value===r.legacy_id||lower(x.textContent)===lower(r.name));if(!o)return;nativeSelect.value=o.value;nativeSelect.dispatchEvent(new Event('change',{bubbles:true}));setSelected(o.value)};
 const row=(r:TemplateRecord,compact=false)=><button type="button" key={r.id} className={`${selected===r.legacy_id?'selected':''} ${compact?'compact':''}`} onClick={()=>choose(r)}><span><b>{r.name}</b><small>{systemsFor(r).join(' · ')||'No system assigned'}</small></span><span className="slr-template-badges">{actionsFor(r).map(x=><em key={x}>{x}</em>)}</span></button>;
 return <>{mount&&createPortal(<section className="slr-template-search"><div className="slr-template-search-controls"><label><span>Search templates</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Start typing to search templates…"/></label><label><span>System</span><select value={system} onChange={e=>setSystem(e.target.value)}><option value="All">All Systems</option>{systems.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Output</span><select value={action} onChange={e=>setAction(e.target.value as ActionFilter)}><option value="All">All Outputs</option><option>RBB</option><option>GC Clarification</option><option>Formal RFI</option><option>Checklist</option></select></label></div><div className="slr-template-search-meta"><b>{searching?visible.length:0}</b><span>{searching?`of ${records.length} matching templates`:`Search or filter to browse ${records.length} templates`}</span>{searching&&<button onClick={()=>{setQuery('');setSystem('All');setAction('All')}}>Clear filters</button>}</div>{searching?(visible.length?<div className="slr-template-search-results">{visible.map(r=>row(r))}</div>:<div className="slr-template-search-empty">No SLR templates match the current filters.</div>):<details className="slr-template-recent"><summary>Recent templates <span>{recent.length}</span></summary><div className="slr-template-search-results compact-results">{recent.map(r=>row(r,true))}</div></details>}</section>,mount)}{quoteMount&&createPortal(<section className="quote-template-search"><input value={quoteQuery} onChange={e=>setQuoteQuery(e.target.value)} placeholder="Search quote templates…"/><select value={quoteSystem} onChange={e=>setQuoteSystem(e.target.value)}><option value="All">All Systems</option>{quoteSystems.map(x=><option key={x}>{x}</option>)}</select><small>{quoteQuery||quoteSystem!=='All'?`${quoteVisibleCount} of ${quoteTotalCount} matches`:`Recent ${Math.min(5,quoteTotalCount)} of ${quoteTotalCount}`}</small>{(quoteQuery||quoteSystem!=='All')&&<button onClick={()=>{setQuoteQuery('');setQuoteSystem('All')}}>Clear</button>}</section>,quoteMount)}{ruleMount&&createPortal(<section className="takeoff-rule-search"><input value={ruleQuery} onChange={e=>setRuleQuery(e.target.value)} placeholder="Search Take Off rules…"/><select value={ruleSystem} onChange={e=>setRuleSystem(e.target.value)}><option value="All">All Systems</option>{ruleSystems.map(x=><option key={x}>{x}</option>)}</select><small>{ruleQuery||ruleSystem!=='All'?`${ruleVisibleCount} of ${ruleTotalCount} matches`:`Recent ${Math.min(5,ruleTotalCount)} of ${ruleTotalCount}`}</small>{(ruleQuery||ruleSystem!=='All')&&<button onClick={()=>{setRuleQuery('');setRuleSystem('All')}}>Clear</button>}</section>,ruleMount)}</>;
}
