'use client';

import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { createClient } from '../lib/supabase/client';

type TemplateRecord = { id:string; legacy_id?:string|null; name:string; active?:boolean; template_data?:Record<string,any>|null };
type ActionFilter = 'All' | 'RBB' | 'GC Clarification' | 'Formal RFI' | 'Checklist';
const text=(value:unknown)=>String(value??'').trim();
const lower=(value:unknown)=>text(value).toLowerCase();
function systemsFor(record:TemplateRecord){const data=record.template_data||{};const systems=Array.isArray(data.systems)?data.systems.map(text).filter(Boolean):[];if(!systems.length&&data.system)systems.push(text(data.system));return Array.from(new Set(systems));}
function actionsFor(record:TemplateRecord){const data=record.template_data||{};const actions:string[]=[];if(data.sow||(data.recommendations&&Object.values(data.recommendations).some((value)=>text(value))))actions.push('RBB');if(data.clarification)actions.push('GC Clarification');if(data.formalRfi||(Array.isArray(data.rfis)&&data.rfis.length))actions.push('Formal RFI');if(data.checklist||text(data.checklistItem)||(data.checklistItems&&Object.values(data.checklistItems).some((value)=>text(value))))actions.push('Checklist');return actions;}
function searchableText(record:TemplateRecord){const data=record.template_data||{};return [record.name,data.title,data.system,...(Array.isArray(data.systems)?data.systems:[]),data.concern,data.basis,data.rfiQuestion,data.reference,data.sourceType,data.checklistItem,JSON.stringify(data.recommendations||{}),JSON.stringify(data.checklistItems||{})].map(lower).join(' ');}

export default function SlrTemplateSearchEnhancer(){
 const [mount,setMount]=useState<HTMLElement|null>(null);const [nativeSelect,setNativeSelect]=useState<HTMLSelectElement|null>(null);const [records,setRecords]=useState<TemplateRecord[]>([]);const [query,setQuery]=useState('');const [system,setSystem]=useState('All');const [action,setAction]=useState<ActionFilter>('All');const [selected,setSelected]=useState('');const [loadError,setLoadError]=useState('');
 const [quoteMount,setQuoteMount]=useState<HTMLElement|null>(null);const [quoteList,setQuoteList]=useState<HTMLElement|null>(null);const [quoteQuery,setQuoteQuery]=useState('');const [quoteSystem,setQuoteSystem]=useState('All');const [quoteSystems,setQuoteSystems]=useState<string[]>([]);const [quoteVisibleCount,setQuoteVisibleCount]=useState(0);const [quoteTotalCount,setQuoteTotalCount]=useState(0);
 useEffect(()=>{let observer:MutationObserver|null=null;const attach=()=>{const bar=document.querySelector<HTMLElement>('.template-library');const select=bar?.querySelector<HTMLSelectElement>('select');if(!bar||!select)return false;let host=bar.querySelector<HTMLElement>('[data-slr-template-search-host]');if(!host){host=document.createElement('div');host.dataset.slrTemplateSearchHost='true';select.before(host);}bar.classList.add('template-library-search-enabled');setMount(host);setNativeSelect(select);setSelected(select.value);select.addEventListener('change',()=>setSelected(select.value));return true;};if(!attach()){observer=new MutationObserver(()=>{if(attach())observer?.disconnect();});observer.observe(document.body,{childList:true,subtree:true});}return()=>observer?.disconnect();},[]);
 useEffect(()=>{let bodyObserver:MutationObserver|null=null;let listObserver:MutationObserver|null=null;const attach=()=>{const list=Array.from(document.querySelectorAll<HTMLElement>('.quote-list')).find((candidate)=>lower(candidate.querySelector('button.primary')?.textContent).includes('new template'));if(!list)return false;let host=list.querySelector<HTMLElement>('[data-quote-template-search-host]');if(!host){host=document.createElement('div');host.dataset.quoteTemplateSearchHost='true';list.querySelector('button.primary')?.after(host);}list.classList.add('quote-template-list-search-enabled');setQuoteMount(host);setQuoteList(list);const refresh=()=>{const values=Array.from(list.querySelectorAll<HTMLButtonElement>(':scope > button:not(.primary)')).map((button)=>text(button.querySelector('small')?.textContent)).filter((value)=>value&&value!=='NEW DRAFT');setQuoteSystems(Array.from(new Set(values)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})));};refresh();listObserver?.disconnect();listObserver=new MutationObserver(refresh);listObserver.observe(list,{childList:true,subtree:true,characterData:true});return true;};if(!attach()){bodyObserver=new MutationObserver(()=>{if(attach())bodyObserver?.disconnect();});bodyObserver.observe(document.body,{childList:true,subtree:true});}return()=>{bodyObserver?.disconnect();listObserver?.disconnect();};},[]);
 useEffect(()=>{if(!quoteList)return;const buttons=Array.from(quoteList.querySelectorAll<HTMLButtonElement>(':scope > button:not(.primary)'));const needle=quoteQuery.trim().toLowerCase();let count=0;for(const button of buttons){const buttonText=lower(button.textContent);const buttonSystem=text(button.querySelector('small')?.textContent);const matches=(!needle||buttonText.includes(needle))&&(quoteSystem==='All'||buttonSystem===quoteSystem);button.hidden=!matches;if(matches)count++;}setQuoteTotalCount(buttons.length);setQuoteVisibleCount(count);},[quoteList,quoteQuery,quoteSystem,quoteSystems]);
 useEffect(()=>{let active=true;void(async()=>{try{const client=createClient();const result=await client.from('slr_templates').select('id,legacy_id,name,template_data,active').eq('active',true).order('name');if(result.error)throw new Error(result.error.message);if(active)setRecords((result.data||[]) as TemplateRecord[]);}catch(error){if(active)setLoadError(error instanceof Error?error.message:'Template library could not be loaded.');}})();return()=>{active=false;};},[]);
 const systems=useMemo(()=>Array.from(new Set(records.flatMap(systemsFor))).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[records]);
 const visible=useMemo(()=>{const needle=query.trim().toLowerCase();return records.filter((record)=>(system==='All'||systemsFor(record).includes(system))&&(action==='All'||actionsFor(record).includes(action))&&(!needle||searchableText(record).includes(needle)));},[records,query,system,action]);
 const choose=(record:TemplateRecord)=>{if(!nativeSelect)return;const preferred=text(record.legacy_id)||record.id;const option=Array.from(nativeSelect.options).find((item)=>item.value===preferred||lower(item.textContent)===lower(record.name));if(!option)return;nativeSelect.value=option.value;nativeSelect.dispatchEvent(new Event('change',{bubbles:true}));setSelected(option.value);};
 return <>{mount&&createPortal(<section className="slr-template-search" aria-label="Search SLR templates"><div className="slr-template-search-controls"><label><span>Search templates</span><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Name, concern, recommendation, RFI text, reference…"/></label><label><span>System</span><select value={system} onChange={(e)=>setSystem(e.target.value)}><option value="All">All</option>{systems.map((item)=><option key={item}>{item}</option>)}</select></label><label><span>Output</span><select value={action} onChange={(e)=>setAction(e.target.value as ActionFilter)}><option value="All">All</option><option>RBB</option><option>GC Clarification</option><option>Formal RFI</option><option>Checklist</option></select></label></div><div className="slr-template-search-meta"><b>{visible.length}</b><span>of {records.length} templates</span>{(query||system!=='All'||action!=='All')&&<button type="button" onClick={()=>{setQuery('');setSystem('All');setAction('All');}}>Clear filters</button>}</div>{loadError?<div className="slr-template-search-empty">Template search could not refresh: {loadError}</div>:visible.length?<div className="slr-template-search-results">{visible.slice(0,100).map((record)=>{const value=text(record.legacy_id)||record.id;const isSelected=selected===value||Array.from(nativeSelect?.options||[]).some((option)=>option.value===selected&&lower(option.textContent)===lower(record.name));return <button type="button" key={record.id} className={isSelected?'selected':''} onClick={()=>choose(record)}><span><b>{record.name}</b><small>{systemsFor(record).join(' · ')||'No system assigned'}</small></span><span className="slr-template-badges">{actionsFor(record).map((item)=><em key={item}>{item}</em>)}</span></button>;})}</div>:<div className="slr-template-search-empty">No SLR templates match the current filters.</div>}{visible.length>100&&<div className="slr-template-search-limit">Showing the first 100 matches. Narrow the search to find a specific template.</div>}</section>,mount)}{quoteMount&&createPortal(<section className="quote-template-search" aria-label="Search quote templates"><input value={quoteQuery} onChange={(e)=>setQuoteQuery(e.target.value)} placeholder="Search quote templates…"/><select value={quoteSystem} onChange={(e)=>setQuoteSystem(e.target.value)}><option value="All">All Systems</option>{quoteSystems.map((item)=><option key={item} value={item}>{item}</option>)}</select><small>{quoteVisibleCount} of {quoteTotalCount} templates</small>{(quoteQuery||quoteSystem!=='All')&&<button type="button" onClick={()=>{setQuoteQuery('');setQuoteSystem('All');}}>Clear</button>}</section>,quoteMount)}</>;
}
