'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { createClient } from '../../../../lib/supabase/client';
import styles from './review-observations.module.css';

type Note={id:string;system_name:string;topic:string;source_type:string;source_reference:string;observation:string;disposition:string;created_at:string};
type Master={project_number:string;name:string;revision:string;status:string};
type GroupBy='system'|'topic'|'source';
const text=(value:unknown)=>String(value??'').trim();
const groupKey=(n:Note,g:GroupBy)=>g==='topic'?(text(n.topic)||'No Topic'):g==='source'?(text(n.source_type)||'No Source Type'):(text(n.system_name)||'No System');

export default function ReviewObservationsClient({masterProjectId}:{masterProjectId:string}){
 const supabase=useMemo(()=>createClient(),[]);const [master,setMaster]=useState<Master|null>(null);const [notes,setNotes]=useState<Note[]>([]);const [search,setSearch]=useState('');const [system,setSystem]=useState('All');const [source,setSource]=useState('All');const [groupBy,setGroupBy]=useState<GroupBy>('system');const [error,setError]=useState('');
 const load=useCallback(async()=>{const [m,n]=await Promise.all([supabase.from('master_projects').select('project_number,name,revision,status').eq('id',masterProjectId).maybeSingle(),supabase.from('master_project_review_notes').select('id,system_name,topic,source_type,source_reference,observation,disposition,created_at').eq('master_project_id',masterProjectId).order('created_at',{ascending:false})]);const e=m.error||n.error;if(e){setError(e.message);return;}setError('');setMaster(m.data as Master|null);setNotes((n.data||[]) as Note[])},[masterProjectId,supabase]);
 useEffect(()=>{void load()},[load]);
 const systems=useMemo(()=>Array.from(new Set(notes.map(n=>text(n.system_name)).filter(Boolean))).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[notes]);const sources=useMemo(()=>Array.from(new Set(notes.map(n=>text(n.source_type)).filter(Boolean))).sort(),[notes]);
 const visible=useMemo(()=>{const needle=search.trim().toLowerCase();return notes.filter(n=>(system==='All'||n.system_name===system)&&(source==='All'||n.source_type===source)&&(!needle||[n.system_name,n.topic,n.source_type,n.source_reference,n.observation,n.disposition].join(' ').toLowerCase().includes(needle)))},[notes,search,system,source]);
 const groups=useMemo(()=>{const map=new Map<string,Note[]>();for(const n of visible){const k=groupKey(n,groupBy);map.set(k,[...(map.get(k)||[]),n])}return [...map.entries()].sort(([a],[b])=>a.localeCompare(b,undefined,{numeric:true}))},[visible,groupBy]);
 return <main className={styles.shell}><header><div><span>DETACHED REVIEW REFERENCE</span><h1>{master?.name||'Review Observations'}</h1><p>{master?`${master.project_number} · ${master.revision} · ${master.status}`:'Loading project…'}</p></div><div><button onClick={()=>void load()}>Refresh</button><button onClick={()=>window.close()}>Close Window</button></div></header><section className={styles.notice}>Use this window as a second-screen reference while manually creating SLRs in the main ScopeLogic window. Review Observations do not create or link SLRs.</section><section className={styles.controls}><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search observation text, topic, source reference…"/><select value={system} onChange={e=>setSystem(e.target.value)}><option value="All">All Systems</option>{systems.map(x=><option key={x}>{x}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value)}><option value="All">All Source Types</option>{sources.map(x=><option key={x}>{x}</option>)}</select><select value={groupBy} onChange={e=>setGroupBy(e.target.value as GroupBy)}><option value="system">Group by System</option><option value="topic">Group by Topic</option><option value="source">Group by Source Type</option></select></section>{error?<div className={styles.error}>{error}</div>:<section className={styles.groups}><div className={styles.count}>{visible.length} of {notes.length} observations · {groups.length} groups</div>{groups.map(([key,items])=><details key={key}><summary><span>▸</span><b>{key}</b><small>{items.length}</small></summary><div>{items.map(n=><article key={n.id}><div className={styles.itemHead}><div><b>{n.topic||'Untitled Observation'}</b><span>{n.system_name} · {n.source_type}</span></div><span>{n.disposition||'Unreviewed'}</span></div><p>{n.observation}</p><footer><b>Reference</b><span>{n.source_reference||'—'}</span></footer></article>)}</div></details>)}{!groups.length?<div className={styles.empty}>No observations match the current filters.</div>:null}</section>}</main>;
}
